//go:build integration

package testdb

import (
	"context"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"portal-berita/backend/internal/content"
	"portal-berita/backend/internal/dbgen"
	"portal-berita/backend/internal/httpx"
)

const heroSlug = "menjaga-keikhlasan-di-tengah-derasnya-arus-informasi"

// TestContentQueriesSmoke runs every Fase 3 query at least once against a
// seeded schema, so SQL that sqlc accepts but PostgreSQL rejects is caught here.
func TestContentQueriesSmoke(t *testing.T) {
	pool := New(t)
	ctx := context.Background()
	q := dbgen.New(pool)
	now := time.Now()
	SeedBase(t, pool)
	SeedDemo(t, pool, now)
	adminID, _, _ := SuperAdmin(t, pool)
	today := httpx.WIBDate(now)

	// --- categories
	cats, err := q.ListCategories(ctx)
	require.NoError(t, err)
	require.Len(t, cats, 13)
	assert.Nil(t, cats[0].ParentID, "roots first")
	withCounts, err := q.ListCategoriesWithCounts(ctx)
	require.NoError(t, err)
	require.Len(t, withCounts, 13)
	var totalPublished int64
	for _, c := range withCounts {
		totalPublished += c.ArticleCount
	}
	kajian, err := q.GetCategoryBySlug(ctx, "kajian")
	require.NoError(t, err)
	fikih, err := q.GetCategoryBySlug(ctx, "fikih")
	require.NoError(t, err)
	require.NotNil(t, fikih.ParentID)
	_, err = q.GetCategory(ctx, kajian.ID)
	require.NoError(t, err)
	n, err := q.CountCategoryChildren(ctx, kajian.ID)
	require.NoError(t, err)
	assert.EqualValues(t, 4, n)
	n, err = q.CountArticlesInCategory(ctx, fikih.ID)
	require.NoError(t, err)
	assert.Positive(t, n)
	newCat, err := q.CreateCategory(ctx, dbgen.CreateCategoryParams{Name: "Uji", Slug: "uji-kat", SortOrder: 99, IsActive: true})
	require.NoError(t, err)
	desc := "d"
	newCat, err = q.UpdateCategory(ctx, dbgen.UpdateCategoryParams{ID: newCat.ID, ParentID: &kajian.ID, Name: "Uji 2", Slug: "uji-kat", Description: &desc, SortOrder: 5, IsActive: true})
	require.NoError(t, err)
	assert.Equal(t, "Uji 2", newCat.Name)
	require.NoError(t, q.UpdateCategoryOrder(ctx, dbgen.UpdateCategoryOrderParams{ID: newCat.ID, SortOrder: 7}))
	rows, err := q.DeleteCategory(ctx, newCat.ID)
	require.NoError(t, err)
	assert.EqualValues(t, 1, rows)

	// --- articles (public)
	published, err := q.CountPublishedArticles(ctx, dbgen.CountPublishedArticlesParams{})
	require.NoError(t, err)
	assert.Equal(t, totalPublished, published)
	list, err := q.ListPublishedArticles(ctx, dbgen.ListPublishedArticlesParams{Limit: 12})
	require.NoError(t, err)
	assert.Len(t, list, 12)
	kajianIDs := []int64{kajian.ID}
	for _, c := range cats {
		if c.ParentID != nil && *c.ParentID == kajian.ID {
			kajianIDs = append(kajianIDs, c.ID)
		}
	}
	yes := true
	inKajian, err := q.ListPublishedArticles(ctx, dbgen.ListPublishedArticlesParams{CategoryIds: kajianIDs, Featured: &yes, Limit: 50})
	require.NoError(t, err)
	for _, a := range inKajian {
		assert.True(t, a.IsFeatured)
	}
	hero, err := q.GetPublishedArticleBySlug(ctx, heroSlug)
	require.NoError(t, err)
	_, err = q.GetArticleBySlugAny(ctx, heroSlug)
	require.NoError(t, err)
	tags, err := q.ListArticleTags(ctx, hero.ID)
	require.NoError(t, err)
	require.NotEmpty(t, tags)
	n, err = q.CountPublishedArticles(ctx, dbgen.CountPublishedArticlesParams{TagID: &tags[0].ID, AuthorID: &hero.AuthorID})
	require.NoError(t, err)
	assert.Positive(t, n)
	other := list[0].ID
	if other == hero.ID {
		other = list[1].ID
	}
	byIDs, err := q.ListPublishedArticlesByIDs(ctx, []int64{hero.ID, other, art0DraftID(t, q)})
	require.NoError(t, err)
	assert.Len(t, byIDs, 2)
	latest, err := q.ListLatestPublishedExcluding(ctx, dbgen.ListLatestPublishedExcludingParams{ExcludeIds: nil, Limit: 3})
	require.NoError(t, err)
	assert.Len(t, latest, 3, "nil exclude_ids must not filter everything")
	latestEx, err := q.ListLatestPublishedExcluding(ctx, dbgen.ListLatestPublishedExcludingParams{ExcludeIds: []int64{latest[0].ID}, Limit: 3})
	require.NoError(t, err)
	assert.NotEqual(t, latest[0].ID, latestEx[0].ID)
	yayasan, err := q.GetCategoryBySlug(ctx, "yayasan")
	require.NoError(t, err)
	timeline, err := q.ListPublishedByCategoryOrdered(ctx, dbgen.ListPublishedByCategoryOrderedParams{CategoryIds: []int64{yayasan.ID}, OrderBy: "event_date", Limit: 3})
	require.NoError(t, err)
	require.NotEmpty(t, timeline)
	assert.NotNil(t, timeline[0].EventDate)
	all, err := q.ListPublishedByCategoryOrdered(ctx, dbgen.ListPublishedByCategoryOrderedParams{TagID: &tags[0].ID, OrderBy: "published_at", ExcludeIds: []int64{hero.ID}, Limit: 5})
	require.NoError(t, err)
	for _, a := range all {
		assert.NotEqual(t, hero.ID, a.ID)
	}
	featured, err := q.ListFeaturedPublished(ctx, dbgen.ListFeaturedPublishedParams{Limit: 1})
	require.NoError(t, err)
	require.Len(t, featured, 1)
	assert.Equal(t, heroSlug, featured[0].Slug)
	breaking, err := q.ListBreakingPublished(ctx, 5)
	require.NoError(t, err)
	assert.NotEmpty(t, breaking)
	related, err := q.ListRelatedArticles(ctx, dbgen.ListRelatedArticlesParams{ArticleID: hero.ID, CategoryID: hero.CategoryID, Limit: 4})
	require.NoError(t, err)
	for _, a := range related {
		assert.NotEqual(t, hero.ID, a.ID)
	}
	sm, err := q.ListPublishedArticlesForSitemap(ctx)
	require.NoError(t, err)
	assert.EqualValues(t, published, len(sm))

	// --- hydrator
	h := content.NewHydrator(pool)
	cards, err := h.Cards(ctx, list)
	require.NoError(t, err)
	require.Len(t, cards, len(list))
	for i, c := range cards {
		assert.Equal(t, list[i].ID, c.ID, "order preserved")
		assert.True(t, strings.HasPrefix(c.URL, "/"+c.Category.Level1Slug()+"/"), c.URL)
		assert.NotEmpty(t, c.Author.Slug)
	}
	adab, err := q.GetPublishedArticleBySlug(ctx, "adab-menuntut-ilmu")
	require.NoError(t, err)
	card, err := h.Card(ctx, adab)
	require.NoError(t, err)
	assert.Equal(t, "/kajian/adab-menuntut-ilmu", card.URL)
	empty, err := h.Cards(ctx, nil)
	require.NoError(t, err)
	assert.NotNil(t, empty)

	// --- articles (admin)
	adminList, err := q.ListArticlesAdmin(ctx, dbgen.ListArticlesAdminParams{Sort: "title", Limit: 100})
	require.NoError(t, err)
	assert.Len(t, adminList, 21)
	assert.LessOrEqual(t, adminList[0].Title, adminList[1].Title)
	for _, sort := range []string{"-title", "published_at", "-published_at", "-view_count", "-updated_at", ""} {
		_, err := q.ListArticlesAdmin(ctx, dbgen.ListArticlesAdminParams{Sort: sort, Limit: 5})
		require.NoError(t, err, sort)
	}
	st := "published"
	qs := "keikhlasan"
	n, err = q.CountArticlesAdmin(ctx, dbgen.CountArticlesAdminParams{Q: &qs, Status: &st, CategoryIds: kajianIDs})
	require.NoError(t, err)
	assert.EqualValues(t, 1, n)
	byStatus, err := q.CountArticlesByStatus(ctx)
	require.NoError(t, err)
	require.NotEmpty(t, byStatus)

	art, err := q.CreateArticle(ctx, dbgen.CreateArticleParams{
		Title: "Uji Smoke", Slug: "uji-smoke", ContentJson: []byte(`{"type":"doc","content":[]}`),
		ContentHtml: "<p>x</p>", ContentText: "x", CategoryID: fikih.ID, AuthorID: adminID,
		Status: content.StatusDraft, ReadingMinutes: 1, CreatedBy: &adminID, UpdatedBy: &adminID,
	})
	require.NoError(t, err)
	exists, err := q.ArticleSlugExists(ctx, dbgen.ArticleSlugExistsParams{Slug: "uji-smoke", ExcludeID: 0})
	require.NoError(t, err)
	assert.True(t, exists)
	exists, err = q.ArticleSlugExists(ctx, dbgen.ArticleSlugExistsParams{Slug: "uji-smoke", ExcludeID: art.ID})
	require.NoError(t, err)
	assert.False(t, exists)
	art, err = q.UpdateArticle(ctx, dbgen.UpdateArticleParams{
		ID: art.ID, Title: "Uji Smoke 2", Slug: "uji-smoke-2", ContentJson: art.ContentJson, ContentHtml: "<p>y</p>",
		ContentText: "y", CategoryID: fikih.ID, AuthorID: adminID, ReadingMinutes: 1, UpdatedBy: &adminID,
	})
	require.NoError(t, err)
	require.NoError(t, q.UpsertSlugRedirect(ctx, dbgen.UpsertSlugRedirectParams{OldSlug: "uji-smoke", ArticleID: art.ID}))
	require.NoError(t, q.UpsertSlugRedirect(ctx, dbgen.UpsertSlugRedirectParams{OldSlug: "uji-smoke", ArticleID: art.ID}))
	red, err := q.GetSlugRedirect(ctx, "uji-smoke")
	require.NoError(t, err)
	assert.Equal(t, art.ID, red.ArticleID)
	require.NoError(t, q.DeleteSlugRedirect(ctx, "uji-smoke"))
	drafts, err := q.ListRecentDrafts(ctx, 5)
	require.NoError(t, err)
	require.NotEmpty(t, drafts)
	assert.Equal(t, art.ID, drafts[0].ID)

	past := now.Add(-time.Minute)
	art, err = q.SetArticleStatus(ctx, dbgen.SetArticleStatusParams{ID: art.ID, Status: content.StatusScheduled, PublishedAt: &past, UpdatedBy: &adminID})
	require.NoError(t, err)
	due, err := q.PublishDueArticles(ctx)
	require.NoError(t, err)
	require.Len(t, due, 1)
	assert.Equal(t, "uji-smoke-2", due[0].Slug)
	art, err = q.SetArticleStatus(ctx, dbgen.SetArticleStatusParams{ID: art.ID, Status: content.StatusDraft})
	require.NoError(t, err)
	require.NotNil(t, art.PublishedAt, "unpublish keeps published_at")
	require.NoError(t, q.IncrementArticleViewCount(ctx, art.ID))
	rows, err = q.SoftDeleteArticle(ctx, art.ID)
	require.NoError(t, err)
	assert.EqualValues(t, 1, rows)
	rows, err = q.SoftDeleteArticle(ctx, art.ID)
	require.NoError(t, err)
	assert.EqualValues(t, 0, rows)
	trashed, err := q.ListArticlesAdmin(ctx, dbgen.ListArticlesAdminParams{Trashed: true, Limit: 10})
	require.NoError(t, err)
	require.Len(t, trashed, 1)
	rows, err = q.RestoreArticle(ctx, art.ID)
	require.NoError(t, err)
	assert.EqualValues(t, 1, rows)
	got, err := q.GetArticle(ctx, art.ID)
	require.NoError(t, err)
	assert.EqualValues(t, 1, got.ViewCount)

	// --- tags
	tagRows, err := q.ListTags(ctx, dbgen.ListTagsParams{Limit: 50})
	require.NoError(t, err)
	require.NotEmpty(t, tagRows)
	cnt, err := q.CountTags(ctx, nil)
	require.NoError(t, err)
	assert.EqualValues(t, len(tagRows), cnt)
	popular, err := q.ListPopularTags(ctx, 3)
	require.NoError(t, err)
	require.NotEmpty(t, popular)
	assert.Positive(t, popular[0].ArticleCount)
	withArticles, err := q.ListTagsWithArticles(ctx)
	require.NoError(t, err)
	require.NotEmpty(t, withArticles)
	bySlug, err := q.GetTagBySlug(ctx, tags[0].Slug)
	require.NoError(t, err)
	assert.Positive(t, bySlug.ArticleCount)
	_, err = q.GetTag(ctx, tags[0].ID)
	require.NoError(t, err)
	t1, err := q.CreateTag(ctx, dbgen.CreateTagParams{Name: "Uji Satu", Slug: "uji-satu"})
	require.NoError(t, err)
	t1b, err := q.GetOrCreateTag(ctx, dbgen.GetOrCreateTagParams{Name: "Uji Satu", Slug: "uji-satu"})
	require.NoError(t, err)
	assert.Equal(t, t1.ID, t1b.ID)
	t2, err := q.GetOrCreateTag(ctx, dbgen.GetOrCreateTagParams{Name: "Uji Dua", Slug: "uji-dua"})
	require.NoError(t, err)
	_, err = q.UpdateTag(ctx, dbgen.UpdateTagParams{ID: t2.ID, Name: "Uji Dua B", Slug: "uji-dua"})
	require.NoError(t, err)
	byTagIDs, err := q.ListTagsByIDs(ctx, []int64{t1.ID, t2.ID})
	require.NoError(t, err)
	assert.Len(t, byTagIDs, 2)
	require.NoError(t, q.AddArticleTags(ctx, dbgen.AddArticleTagsParams{ArticleID: art.ID, TagIds: []int64{t1.ID, t2.ID}}))
	require.NoError(t, q.MergeTagArticles(ctx, dbgen.MergeTagArticlesParams{FromID: t1.ID, IntoID: t2.ID}))
	rows, err = q.DeleteTag(ctx, t1.ID)
	require.NoError(t, err)
	assert.EqualValues(t, 1, rows)
	links, err := q.ListArticleTagsByArticleIDs(ctx, []int64{art.ID, hero.ID})
	require.NoError(t, err)
	assert.GreaterOrEqual(t, len(links), 2)
	require.NoError(t, q.DeleteArticleTags(ctx, art.ID))

	// --- analytics
	inserted, err := q.InsertViewDedup(ctx, dbgen.InsertViewDedupParams{ArticleID: hero.ID, VisitorHash: []byte("h"), Day: today})
	require.NoError(t, err)
	assert.EqualValues(t, 1, inserted)
	inserted, err = q.InsertViewDedup(ctx, dbgen.InsertViewDedupParams{ArticleID: hero.ID, VisitorHash: []byte("h"), Day: today})
	require.NoError(t, err)
	assert.EqualValues(t, 0, inserted, "duplicate")
	inserted, err = q.InsertViewDedup(ctx, dbgen.InsertViewDedupParams{ArticleID: art.ID, VisitorHash: []byte("h"), Day: today})
	require.NoError(t, err)
	assert.EqualValues(t, 0, inserted, "draft article ignored")
	require.NoError(t, q.UpsertDailyView(ctx, dbgen.UpsertDailyViewParams{ArticleID: hero.ID, Day: today}))
	require.NoError(t, q.UpsertDailyView(ctx, dbgen.UpsertDailyViewParams{ArticleID: hero.ID, Day: today}))
	top, err := q.ListTopArticleViews(ctx, dbgen.ListTopArticleViewsParams{FromDay: today.AddDate(0, 0, -1), ToDay: today, Limit: 5})
	require.NoError(t, err)
	require.NotEmpty(t, top)
	assert.Equal(t, hero.ID, top[0].ArticleID)
	sum, err := q.SumViewsBetween(ctx, dbgen.SumViewsBetweenParams{FromDay: today.AddDate(0, 0, -6), ToDay: today})
	require.NoError(t, err)
	assert.Positive(t, sum)
	daily, err := q.ListDailyViewTotals(ctx, dbgen.ListDailyViewTotalsParams{FromDay: today.AddDate(0, 0, -13), ToDay: today})
	require.NoError(t, err)
	require.Len(t, daily, 14, "zero-filled")
	assert.Equal(t, today.Format("2006-01-02"), daily[13].Day.Format("2006-01-02"))
	deleted, err := q.DeleteOldViewDedup(ctx, today.AddDate(0, 0, 1))
	require.NoError(t, err)
	assert.EqualValues(t, 1, deleted)

	// --- search
	hits, err := q.SearchArticles(ctx, dbgen.SearchArticlesParams{Query: "keikhlasan", Limit: 10})
	require.NoError(t, err)
	require.NotEmpty(t, hits)
	assert.Equal(t, hero.ID, hits[0].ID)
	n, err = q.CountSearchArticles(ctx, "keikhlasan")
	require.NoError(t, err)
	assert.EqualValues(t, len(hits), n)
	n, err = q.CountSearchArticles(ctx, "keiklasan")
	require.NoError(t, err)
	assert.Zero(t, n)
	fuzzy, err := q.SearchArticlesFuzzy(ctx, dbgen.SearchArticlesFuzzyParams{Query: "keiklasan", Limit: 10})
	require.NoError(t, err)
	require.NotEmpty(t, fuzzy)
	assert.Equal(t, hero.ID, fuzzy[0].ID)
	n, err = q.CountSearchArticlesFuzzy(ctx, "keiklasan")
	require.NoError(t, err)
	assert.EqualValues(t, len(fuzzy), n)

	// --- media
	logoRefs := int64(0)
	medias, err := q.ListMedia(ctx, dbgen.ListMediaParams{Limit: 10})
	require.NoError(t, err)
	require.Len(t, medias, 1)
	logoRefs, err = q.CountMediaReferences(ctx, medias[0].ID)
	require.NoError(t, err)
	assert.EqualValues(t, 1, logoRefs, "site.identity logo_media_id")
	w, hgt := int32(10), int32(20)
	m, err := q.CreateMedia(ctx, dbgen.CreateMediaParams{StorageKey: "2026/09/x.png", Url: "/uploads/2026/09/x.png", OriginalName: "x.png", MimeType: "image/png", SizeBytes: 3, Width: &w, Height: &hgt, UploadedBy: &adminID})
	require.NoError(t, err)
	prefix := "image/"
	n, err = q.CountMedia(ctx, dbgen.CountMediaParams{MimePrefix: &prefix})
	require.NoError(t, err)
	assert.EqualValues(t, 2, n)
	alt := "alt"
	m, err = q.UpdateMediaMeta(ctx, dbgen.UpdateMediaMetaParams{ID: m.ID, AltText: &alt})
	require.NoError(t, err)
	assert.Equal(t, "alt", *m.AltText)
	_, err = q.GetMedia(ctx, m.ID)
	require.NoError(t, err)
	byMedia, err := q.ListMediaByIDs(ctx, []int64{m.ID})
	require.NoError(t, err)
	assert.Len(t, byMedia, 1)
	Exec(t, pool, "UPDATE articles SET cover_media_id = $1, og_media_id = $1 WHERE id = $2", m.ID, art.ID)
	refs, err := q.CountMediaReferences(ctx, m.ID)
	require.NoError(t, err)
	assert.EqualValues(t, 1, refs, "counts referencing rows, not columns")
	Exec(t, pool, "UPDATE articles SET cover_media_id = NULL, og_media_id = NULL WHERE id = $1", art.ID)
	rows, err = q.DeleteMedia(ctx, m.ID)
	require.NoError(t, err)
	assert.EqualValues(t, 1, rows)

	// --- events
	upcoming, err := q.ListUpcomingEvents(ctx, 3)
	require.NoError(t, err)
	assert.Len(t, upcoming, 3)
	for _, when := range []string{"upcoming", "past", "all"} {
		evs, err := q.ListPublishedEvents(ctx, dbgen.ListPublishedEventsParams{When: when, Limit: 10})
		require.NoError(t, err, when)
		c, err := q.CountPublishedEvents(ctx, dbgen.CountPublishedEventsParams{When: when})
		require.NoError(t, err, when)
		assert.EqualValues(t, len(evs), c, when)
	}
	from, to := now.AddDate(0, -2, 0), now.AddDate(0, 3, 0)
	between, err := q.ListPublishedEventsBetween(ctx, dbgen.ListPublishedEventsBetweenParams{FromTs: from, ToTs: to})
	require.NoError(t, err)
	assert.NotEmpty(t, between)
	_, err = q.ListPublishedEvents(ctx, dbgen.ListPublishedEventsParams{When: "all", MonthFrom: &from, MonthTo: &to, Limit: 10})
	require.NoError(t, err)
	evSitemap, err := q.ListPublishedEventsForSitemap(ctx)
	require.NoError(t, err)
	assert.NotEmpty(t, evSitemap)
	_, err = q.GetPublishedEventBySlug(ctx, upcoming[0].Slug)
	require.NoError(t, err)
	_, err = q.GetEventBySlug(ctx, upcoming[0].Slug)
	require.NoError(t, err)
	ev, err := q.CreateEvent(ctx, dbgen.CreateEventParams{Title: "Uji", Slug: "uji-event", StartsAt: now, LocationName: "Masjid", Status: "draft", CreatedBy: &adminID})
	require.NoError(t, err)
	ev, err = q.UpdateEvent(ctx, dbgen.UpdateEventParams{ID: ev.ID, Title: "Uji 2", Slug: "uji-event", StartsAt: now, LocationName: "Aula", Status: "draft"})
	require.NoError(t, err)
	exists, err = q.EventSlugExists(ctx, dbgen.EventSlugExistsParams{Slug: "uji-event", ExcludeID: ev.ID})
	require.NoError(t, err)
	assert.False(t, exists)
	evAdmin, err := q.ListEventsAdmin(ctx, dbgen.ListEventsAdminParams{Limit: 50})
	require.NoError(t, err)
	n, err = q.CountEventsAdmin(ctx, dbgen.CountEventsAdminParams{})
	require.NoError(t, err)
	assert.EqualValues(t, len(evAdmin), n)
	_, err = q.GetEvent(ctx, ev.ID)
	require.NoError(t, err)
	_, err = q.GetPublishedEventBySlug(ctx, "uji-event")
	assert.Error(t, err, "draft hidden")
	eventCards, err := h.EventCards(ctx, upcoming)
	require.NoError(t, err)
	assert.Equal(t, "/agenda/"+upcoming[0].Slug, eventCards[0].URL)
	rows, err = q.DeleteEvent(ctx, ev.ID)
	require.NoError(t, err)
	assert.EqualValues(t, 1, rows)

	// --- alumni
	alumni, err := q.ListPublishedAlumni(ctx, dbgen.ListPublishedAlumniParams{Featured: &yes, Limit: 10})
	require.NoError(t, err)
	assert.Len(t, alumni, 4)
	n, err = q.CountPublishedAlumni(ctx, nil)
	require.NoError(t, err)
	assert.GreaterOrEqual(t, n, int64(4))
	_, err = q.GetPublishedAlumniBySlug(ctx, alumni[0].Slug)
	require.NoError(t, err)
	_, err = q.GetAlumniBySlug(ctx, alumni[0].Slug)
	require.NoError(t, err)
	al, err := q.CreateAlumni(ctx, dbgen.CreateAlumniParams{Name: "Uji", Slug: "uji-alumni", RoleTitle: "R", ShortBio: "B", Status: "draft"})
	require.NoError(t, err)
	_, err = q.UpdateAlumni(ctx, dbgen.UpdateAlumniParams{ID: al.ID, Name: "Uji 2", Slug: "uji-alumni", RoleTitle: "R", ShortBio: "B", Status: "draft"})
	require.NoError(t, err)
	require.NoError(t, q.UpdateAlumniOrder(ctx, dbgen.UpdateAlumniOrderParams{ID: al.ID, SortOrder: 3}))
	_, err = q.AlumniSlugExists(ctx, dbgen.AlumniSlugExistsParams{Slug: "uji-alumni"})
	require.NoError(t, err)
	alAdmin, err := q.ListAlumniAdmin(ctx, dbgen.ListAlumniAdminParams{Limit: 50})
	require.NoError(t, err)
	n, err = q.CountAlumniAdmin(ctx, dbgen.CountAlumniAdminParams{})
	require.NoError(t, err)
	assert.EqualValues(t, len(alAdmin), n)
	_, err = q.GetAlumni(ctx, al.ID)
	require.NoError(t, err)
	_, err = q.ListPublishedAlumniForSitemap(ctx)
	require.NoError(t, err)
	alumniCards, err := h.AlumniCards(ctx, alumni)
	require.NoError(t, err)
	assert.Equal(t, "/tokoh/"+alumni[0].Slug, alumniCards[0].URL)
	_, err = q.DeleteAlumni(ctx, al.ID)
	require.NoError(t, err)

	// --- videos
	videos, err := q.ListPublishedVideos(ctx, dbgen.ListPublishedVideosParams{Limit: 10})
	require.NoError(t, err)
	assert.Len(t, videos, 3)
	assert.True(t, videos[0].IsFeatured)
	others, err := q.ListPublishedVideos(ctx, dbgen.ListPublishedVideosParams{ExcludeID: &videos[0].ID, Limit: 6})
	require.NoError(t, err)
	assert.Len(t, others, 2)
	n, err = q.CountPublishedVideos(ctx, nil)
	require.NoError(t, err)
	assert.EqualValues(t, 3, n)
	_, err = q.GetPublishedVideoBySlug(ctx, videos[0].Slug)
	require.NoError(t, err)
	_, err = q.GetVideoBySlug(ctx, videos[0].Slug)
	require.NoError(t, err)
	v, err := q.CreateVideo(ctx, dbgen.CreateVideoParams{Title: "Uji", Slug: "uji-video", YoutubeID: "abcdefghijk", Status: "draft"})
	require.NoError(t, err)
	assert.False(t, v.PublishedAt.IsZero(), "published_at defaults to now")
	v2, err := q.UpdateVideo(ctx, dbgen.UpdateVideoParams{ID: v.ID, Title: "Uji 2", Slug: "uji-video", YoutubeID: "abcdefghijk", Status: "draft"})
	require.NoError(t, err)
	assert.True(t, v.PublishedAt.Equal(v2.PublishedAt), "published_at kept")
	_, err = q.VideoSlugExists(ctx, dbgen.VideoSlugExistsParams{Slug: "uji-video"})
	require.NoError(t, err)
	vAdmin, err := q.ListVideosAdmin(ctx, dbgen.ListVideosAdminParams{Limit: 50})
	require.NoError(t, err)
	n, err = q.CountVideosAdmin(ctx, dbgen.CountVideosAdminParams{})
	require.NoError(t, err)
	assert.EqualValues(t, len(vAdmin), n)
	_, err = q.GetVideo(ctx, v.ID)
	require.NoError(t, err)
	_, err = q.ListPublishedVideosForSitemap(ctx)
	require.NoError(t, err)
	videoCards, err := h.VideoCards(ctx, videos)
	require.NoError(t, err)
	assert.Contains(t, videoCards[0].ThumbnailURL, "i.ytimg.com")
	_, err = q.DeleteVideo(ctx, v.ID)
	require.NoError(t, err)

	// --- pages
	page, err := q.GetPublishedPageBySlug(ctx, "profil-yayasan")
	require.NoError(t, err)
	_, err = q.GetPageBySlug(ctx, page.Slug)
	require.NoError(t, err)
	_, err = q.GetPage(ctx, page.ID)
	require.NoError(t, err)
	pages, err := q.ListPages(ctx)
	require.NoError(t, err)
	pubPages, err := q.ListPublishedPages(ctx)
	require.NoError(t, err)
	assert.NotEmpty(t, pubPages)
	assert.GreaterOrEqual(t, len(pages), len(pubPages))
	p, err := q.CreatePage(ctx, dbgen.CreatePageParams{Title: "Uji", Slug: "uji-page", ContentJson: []byte(`{"type":"doc"}`), ContentHtml: "", Status: "draft"})
	require.NoError(t, err)
	_, err = q.UpdatePage(ctx, dbgen.UpdatePageParams{ID: p.ID, Title: "Uji 2", Slug: "uji-page", ContentJson: p.ContentJson, Status: "draft"})
	require.NoError(t, err)
	_, err = q.PageSlugExists(ctx, dbgen.PageSlugExistsParams{Slug: "uji-page"})
	require.NoError(t, err)
	_, err = q.DeletePage(ctx, p.ID)
	require.NoError(t, err)

	// --- snippets
	faq := "faq"
	faqs, err := q.ListActiveSnippets(ctx, dbgen.ListActiveSnippetsParams{Type: &faq, Now: now})
	require.NoError(t, err)
	assert.Len(t, faqs, 3)
	activeAll, err := q.ListActiveSnippets(ctx, dbgen.ListActiveSnippetsParams{Now: now})
	require.NoError(t, err)
	assert.Greater(t, len(activeAll), 3)
	adminSnips, err := q.ListSnippetsAdmin(ctx, nil)
	require.NoError(t, err)
	assert.GreaterOrEqual(t, len(adminSnips), len(activeAll))
	start := now.Add(-30 * time.Second)
	sn, err := q.CreateSnippet(ctx, dbgen.CreateSnippetParams{Type: "announcement", Body: "Uji", IsActive: true, StartsAt: &start})
	require.NoError(t, err)
	_, err = q.UpdateSnippet(ctx, dbgen.UpdateSnippetParams{ID: sn.ID, Type: "announcement", Body: "Uji 2", IsActive: true, StartsAt: &start})
	require.NoError(t, err)
	require.NoError(t, q.UpdateSnippetOrder(ctx, dbgen.UpdateSnippetOrderParams{ID: sn.ID, SortOrder: 9}))
	trans, err := q.CountSnippetTransitions(ctx, dbgen.CountSnippetTransitionsParams{Since: now.Add(-time.Minute), Now: now})
	require.NoError(t, err)
	assert.EqualValues(t, 1, trans)
	_, err = q.GetSnippet(ctx, sn.ID)
	require.NoError(t, err)
	_, err = q.DeleteSnippet(ctx, sn.ID)
	require.NoError(t, err)

	// --- homepage
	ids, err := q.ListHomepageSectionIDs(ctx, "home")
	require.NoError(t, err)
	require.Len(t, ids, 13)
	maxPos, err := q.MaxHomepagePosition(ctx, "home")
	require.NoError(t, err)
	sec, err := q.CreateHomepageSection(ctx, dbgen.CreateHomepageSectionParams{Type: "rich_text", Label: "Uji", Position: maxPos + 10, IsActive: true, Config: []byte(`{}`), PageKey: "home", UpdatedBy: &adminID})
	require.NoError(t, err)
	_, err = q.UpdateHomepageSection(ctx, dbgen.UpdateHomepageSectionParams{ID: sec.ID, Label: "Uji 2", IsActive: false, Config: []byte(`{"content_html":""}`)})
	require.NoError(t, err)
	_, err = q.GetHomepageSection(ctx, sec.ID)
	require.NoError(t, err)
	// Two-pass renumber: new section first.
	order := append([]int64{sec.ID}, ids...)
	tx, err := pool.Begin(ctx)
	require.NoError(t, err)
	qtx := dbgen.New(tx)
	for i, id := range order {
		require.NoError(t, qtx.UpdateHomepageSectionPosition(ctx, dbgen.UpdateHomepageSectionPositionParams{ID: id, Position: int32(-(i + 1) * 10)}))
	}
	for i, id := range order {
		require.NoError(t, qtx.UpdateHomepageSectionPosition(ctx, dbgen.UpdateHomepageSectionPositionParams{ID: id, Position: int32((i + 1) * 10)}))
	}
	require.NoError(t, tx.Commit(ctx))
	ids2, err := q.ListHomepageSectionIDs(ctx, "home")
	require.NoError(t, err)
	assert.Equal(t, sec.ID, ids2[0])
	rows, err = q.DeleteHomepageSection(ctx, sec.ID)
	require.NoError(t, err)
	assert.EqualValues(t, 1, rows)

	// --- menus
	menus, err := q.ListMenus(ctx)
	require.NoError(t, err)
	assert.Len(t, menus, 4)
	header, err := q.GetMenuByCode(ctx, "header")
	require.NoError(t, err)
	items, err := q.ListMenuItems(ctx, header.ID)
	require.NoError(t, err)
	require.NotEmpty(t, items)
	allItems, err := q.ListAllMenuItems(ctx)
	require.NoError(t, err)
	assert.Len(t, allItems, 19)
	tx, err = pool.Begin(ctx)
	require.NoError(t, err)
	qtx = dbgen.New(tx)
	require.NoError(t, qtx.DeleteMenuItems(ctx, header.ID))
	parentID, err := qtx.CreateMenuItem(ctx, dbgen.CreateMenuItemParams{MenuID: header.ID, Label: "Beranda", LinkType: "route", LinkTarget: "/", IsActive: true})
	require.NoError(t, err)
	_, err = qtx.CreateMenuItem(ctx, dbgen.CreateMenuItemParams{MenuID: header.ID, ParentID: &parentID, Label: "Kajian", LinkType: "category", LinkTarget: "kajian", SortOrder: 1, IsActive: true})
	require.NoError(t, err)
	require.NoError(t, tx.Rollback(ctx))

	// --- users
	authors, err := q.ListAuthorsWithPublishedArticles(ctx)
	require.NoError(t, err)
	require.NotEmpty(t, authors)
	users, err := q.ListUsersByIDs(ctx, []int64{adminID, hero.AuthorID})
	require.NoError(t, err)
	assert.Len(t, users, 2)
}

// art0DraftID returns the id of a non-public article (none in the demo seed
// → 0), used to check ListPublishedArticlesByIDs filters by the predicate.
func art0DraftID(t *testing.T, q *dbgen.Queries) int64 {
	t.Helper()
	st := content.StatusDraft
	rows, err := q.ListArticlesAdmin(context.Background(), dbgen.ListArticlesAdminParams{Status: &st, Limit: 1})
	require.NoError(t, err)
	if len(rows) == 0 {
		return 0
	}
	return rows[0].ID
}
