// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alumni.sql

package dbgen

import (
	"context"
	"time"
)

const alumniSlugExists = `-- name: AlumniSlugExists :one
SELECT EXISTS (
  SELECT 1 FROM alumni_profiles WHERE slug = $1::text AND id <> $2::bigint
) AS exists
`

type AlumniSlugExistsParams struct {
	Slug      string `json:"slug"`
	ExcludeID int64  `json:"exclude_id"`
}

func (q *Queries) AlumniSlugExists(ctx context.Context, arg AlumniSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, alumniSlugExists, arg.Slug, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAlumniAdmin = `-- name: CountAlumniAdmin :one
SELECT count(*) FROM alumni_profiles
WHERE ($1::text IS NULL OR name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR status = $2::text)
`

type CountAlumniAdminParams struct {
	Q      *string `json:"q"`
	Status *string `json:"status"`
}

func (q *Queries) CountAlumniAdmin(ctx context.Context, arg CountAlumniAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAlumniAdmin, arg.Q, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedAlumni = `-- name: CountPublishedAlumni :one
SELECT count(*) FROM alumni_profiles
WHERE status = 'published'
  AND ($1::bool IS NULL OR is_featured = $1::bool)
`

func (q *Queries) CountPublishedAlumni(ctx context.Context, featured *bool) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedAlumni, featured)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlumni = `-- name: CreateAlumni :one
INSERT INTO alumni_profiles (
  name, slug, role_title, class_year, short_bio, story_json, story_html, photo_media_id,
  is_featured, sort_order, status, seo_title, seo_description, created_by, updated_by)
VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8,
  $9, $10, $11,
  $12, $13, $14, $15)
RETURNING id, name, slug, role_title, class_year, short_bio, story_json, story_html, photo_media_id, is_featured, sort_order, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at
`

type CreateAlumniParams struct {
	Name           string  `json:"name"`
	Slug           string  `json:"slug"`
	RoleTitle      string  `json:"role_title"`
	ClassYear      *int16  `json:"class_year"`
	ShortBio       string  `json:"short_bio"`
	StoryJson      []byte  `json:"story_json"`
	StoryHtml      *string `json:"story_html"`
	PhotoMediaID   *int64  `json:"photo_media_id"`
	IsFeatured     bool    `json:"is_featured"`
	SortOrder      int32   `json:"sort_order"`
	Status         string  `json:"status"`
	SeoTitle       *string `json:"seo_title"`
	SeoDescription *string `json:"seo_description"`
	CreatedBy      *int64  `json:"created_by"`
	UpdatedBy      *int64  `json:"updated_by"`
}

func (q *Queries) CreateAlumni(ctx context.Context, arg CreateAlumniParams) (AlumniProfile, error) {
	row := q.db.QueryRow(ctx, createAlumni,
		arg.Name,
		arg.Slug,
		arg.RoleTitle,
		arg.ClassYear,
		arg.ShortBio,
		arg.StoryJson,
		arg.StoryHtml,
		arg.PhotoMediaID,
		arg.IsFeatured,
		arg.SortOrder,
		arg.Status,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i AlumniProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.RoleTitle,
		&i.ClassYear,
		&i.ShortBio,
		&i.StoryJson,
		&i.StoryHtml,
		&i.PhotoMediaID,
		&i.IsFeatured,
		&i.SortOrder,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAlumni = `-- name: DeleteAlumni :execrows
DELETE FROM alumni_profiles WHERE id = $1
`

func (q *Queries) DeleteAlumni(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAlumni, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAlumni = `-- name: GetAlumni :one
SELECT id, name, slug, role_title, class_year, short_bio, story_json, story_html, photo_media_id, is_featured, sort_order, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM alumni_profiles WHERE id = $1
`

func (q *Queries) GetAlumni(ctx context.Context, id int64) (AlumniProfile, error) {
	row := q.db.QueryRow(ctx, getAlumni, id)
	var i AlumniProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.RoleTitle,
		&i.ClassYear,
		&i.ShortBio,
		&i.StoryJson,
		&i.StoryHtml,
		&i.PhotoMediaID,
		&i.IsFeatured,
		&i.SortOrder,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAlumniBySlug = `-- name: GetAlumniBySlug :one
SELECT id, name, slug, role_title, class_year, short_bio, story_json, story_html, photo_media_id, is_featured, sort_order, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM alumni_profiles WHERE slug = $1
`

func (q *Queries) GetAlumniBySlug(ctx context.Context, slug string) (AlumniProfile, error) {
	row := q.db.QueryRow(ctx, getAlumniBySlug, slug)
	var i AlumniProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.RoleTitle,
		&i.ClassYear,
		&i.ShortBio,
		&i.StoryJson,
		&i.StoryHtml,
		&i.PhotoMediaID,
		&i.IsFeatured,
		&i.SortOrder,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedAlumniBySlug = `-- name: GetPublishedAlumniBySlug :one
SELECT id, name, slug, role_title, class_year, short_bio, story_json, story_html, photo_media_id, is_featured, sort_order, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM alumni_profiles WHERE slug = $1 AND status = 'published'
`

func (q *Queries) GetPublishedAlumniBySlug(ctx context.Context, slug string) (AlumniProfile, error) {
	row := q.db.QueryRow(ctx, getPublishedAlumniBySlug, slug)
	var i AlumniProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.RoleTitle,
		&i.ClassYear,
		&i.ShortBio,
		&i.StoryJson,
		&i.StoryHtml,
		&i.PhotoMediaID,
		&i.IsFeatured,
		&i.SortOrder,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlumniAdmin = `-- name: ListAlumniAdmin :many
SELECT id, name, slug, role_title, class_year, short_bio, story_json, story_html, photo_media_id, is_featured, sort_order, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM alumni_profiles
WHERE ($1::text IS NULL OR name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY sort_order, id
LIMIT $4 OFFSET $3
`

type ListAlumniAdminParams struct {
	Q      *string `json:"q"`
	Status *string `json:"status"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) ListAlumniAdmin(ctx context.Context, arg ListAlumniAdminParams) ([]AlumniProfile, error) {
	rows, err := q.db.Query(ctx, listAlumniAdmin,
		arg.Q,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlumniProfile{}
	for rows.Next() {
		var i AlumniProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.RoleTitle,
			&i.ClassYear,
			&i.ShortBio,
			&i.StoryJson,
			&i.StoryHtml,
			&i.PhotoMediaID,
			&i.IsFeatured,
			&i.SortOrder,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedAlumni = `-- name: ListPublishedAlumni :many
SELECT id, name, slug, role_title, class_year, short_bio, story_json, story_html, photo_media_id, is_featured, sort_order, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM alumni_profiles
WHERE status = 'published'
  AND ($1::bool IS NULL OR is_featured = $1::bool)
ORDER BY sort_order, id
LIMIT $3 OFFSET $2
`

type ListPublishedAlumniParams struct {
	Featured *bool `json:"featured"`
	Offset   int32 `json:"offset"`
	Limit    int32 `json:"limit"`
}

func (q *Queries) ListPublishedAlumni(ctx context.Context, arg ListPublishedAlumniParams) ([]AlumniProfile, error) {
	rows, err := q.db.Query(ctx, listPublishedAlumni, arg.Featured, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlumniProfile{}
	for rows.Next() {
		var i AlumniProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.RoleTitle,
			&i.ClassYear,
			&i.ShortBio,
			&i.StoryJson,
			&i.StoryHtml,
			&i.PhotoMediaID,
			&i.IsFeatured,
			&i.SortOrder,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedAlumniForSitemap = `-- name: ListPublishedAlumniForSitemap :many
SELECT slug, updated_at FROM alumni_profiles
WHERE status = 'published'
ORDER BY sort_order, id
`

type ListPublishedAlumniForSitemapRow struct {
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListPublishedAlumniForSitemap(ctx context.Context) ([]ListPublishedAlumniForSitemapRow, error) {
	rows, err := q.db.Query(ctx, listPublishedAlumniForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedAlumniForSitemapRow{}
	for rows.Next() {
		var i ListPublishedAlumniForSitemapRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAlumni = `-- name: UpdateAlumni :one
UPDATE alumni_profiles
SET name = $1,
    slug = $2,
    role_title = $3,
    class_year = $4,
    short_bio = $5,
    story_json = $6,
    story_html = $7,
    photo_media_id = $8,
    is_featured = $9,
    sort_order = $10,
    status = $11,
    seo_title = $12,
    seo_description = $13,
    updated_by = $14
WHERE id = $15
RETURNING id, name, slug, role_title, class_year, short_bio, story_json, story_html, photo_media_id, is_featured, sort_order, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at
`

type UpdateAlumniParams struct {
	Name           string  `json:"name"`
	Slug           string  `json:"slug"`
	RoleTitle      string  `json:"role_title"`
	ClassYear      *int16  `json:"class_year"`
	ShortBio       string  `json:"short_bio"`
	StoryJson      []byte  `json:"story_json"`
	StoryHtml      *string `json:"story_html"`
	PhotoMediaID   *int64  `json:"photo_media_id"`
	IsFeatured     bool    `json:"is_featured"`
	SortOrder      int32   `json:"sort_order"`
	Status         string  `json:"status"`
	SeoTitle       *string `json:"seo_title"`
	SeoDescription *string `json:"seo_description"`
	UpdatedBy      *int64  `json:"updated_by"`
	ID             int64   `json:"id"`
}

func (q *Queries) UpdateAlumni(ctx context.Context, arg UpdateAlumniParams) (AlumniProfile, error) {
	row := q.db.QueryRow(ctx, updateAlumni,
		arg.Name,
		arg.Slug,
		arg.RoleTitle,
		arg.ClassYear,
		arg.ShortBio,
		arg.StoryJson,
		arg.StoryHtml,
		arg.PhotoMediaID,
		arg.IsFeatured,
		arg.SortOrder,
		arg.Status,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.UpdatedBy,
		arg.ID,
	)
	var i AlumniProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.RoleTitle,
		&i.ClassYear,
		&i.ShortBio,
		&i.StoryJson,
		&i.StoryHtml,
		&i.PhotoMediaID,
		&i.IsFeatured,
		&i.SortOrder,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAlumniOrder = `-- name: UpdateAlumniOrder :exec
UPDATE alumni_profiles SET sort_order = $1 WHERE id = $2
`

type UpdateAlumniOrderParams struct {
	SortOrder int32 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateAlumniOrder(ctx context.Context, arg UpdateAlumniOrderParams) error {
	_, err := q.db.Exec(ctx, updateAlumniOrder, arg.SortOrder, arg.ID)
	return err
}
