// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package dbgen

import (
	"context"
	"time"
)

const deleteOldViewDedup = `-- name: DeleteOldViewDedup :execrows
DELETE FROM article_view_dedup WHERE day < $1
`

func (q *Queries) DeleteOldViewDedup(ctx context.Context, day time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldViewDedup, day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertViewDedup = `-- name: InsertViewDedup :execrows
INSERT INTO article_view_dedup (article_id, visitor_hash, day)
SELECT a.id, $1::bytea, $2::date
FROM articles a
WHERE a.id = $3::bigint
  AND a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
ON CONFLICT DO NOTHING
`

type InsertViewDedupParams struct {
	VisitorHash []byte    `json:"visitor_hash"`
	Day         time.Time `json:"day"`
	ArticleID   int64     `json:"article_id"`
}

// InsertViewDedup records one visitor/day for a published article. 0 rows =
// duplicate or not a public article.
func (q *Queries) InsertViewDedup(ctx context.Context, arg InsertViewDedupParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertViewDedup, arg.VisitorHash, arg.Day, arg.ArticleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDailyViewTotals = `-- name: ListDailyViewTotals :many
SELECT d.day::date AS day, COALESCE(sum(v.views), 0)::bigint AS views
FROM generate_series($1::date, $2::date, interval '1 day') AS d(day)
LEFT JOIN article_views_daily v ON v.day = d.day::date
GROUP BY d.day
ORDER BY d.day
`

type ListDailyViewTotalsParams struct {
	FromDay time.Time `json:"from_day"`
	ToDay   time.Time `json:"to_day"`
}

type ListDailyViewTotalsRow struct {
	Day   time.Time `json:"day"`
	Views int64     `json:"views"`
}

// ListDailyViewTotals returns one row per day in [from_day, to_day] (zero-filled).
func (q *Queries) ListDailyViewTotals(ctx context.Context, arg ListDailyViewTotalsParams) ([]ListDailyViewTotalsRow, error) {
	rows, err := q.db.Query(ctx, listDailyViewTotals, arg.FromDay, arg.ToDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyViewTotalsRow{}
	for rows.Next() {
		var i ListDailyViewTotalsRow
		if err := rows.Scan(&i.Day, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopArticleViews = `-- name: ListTopArticleViews :many
SELECT v.article_id, sum(v.views)::bigint AS views
FROM article_views_daily v
JOIN articles a ON a.id = v.article_id
WHERE v.day BETWEEN $1::date AND $2::date
  AND a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
GROUP BY v.article_id, a.published_at
ORDER BY sum(v.views) DESC, a.published_at DESC, v.article_id DESC
LIMIT $3
`

type ListTopArticleViewsParams struct {
	FromDay time.Time `json:"from_day"`
	ToDay   time.Time `json:"to_day"`
	Limit   int32     `json:"limit"`
}

type ListTopArticleViewsRow struct {
	ArticleID int64 `json:"article_id"`
	Views     int64 `json:"views"`
}

// ListTopArticleViews: published articles by summed views with day in [from_day, to_day].
func (q *Queries) ListTopArticleViews(ctx context.Context, arg ListTopArticleViewsParams) ([]ListTopArticleViewsRow, error) {
	rows, err := q.db.Query(ctx, listTopArticleViews, arg.FromDay, arg.ToDay, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopArticleViewsRow{}
	for rows.Next() {
		var i ListTopArticleViewsRow
		if err := rows.Scan(&i.ArticleID, &i.Views); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumViewsBetween = `-- name: SumViewsBetween :one
SELECT COALESCE(sum(views), 0)::bigint AS views
FROM article_views_daily
WHERE day BETWEEN $1::date AND $2::date
`

type SumViewsBetweenParams struct {
	FromDay time.Time `json:"from_day"`
	ToDay   time.Time `json:"to_day"`
}

func (q *Queries) SumViewsBetween(ctx context.Context, arg SumViewsBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumViewsBetween, arg.FromDay, arg.ToDay)
	var views int64
	err := row.Scan(&views)
	return views, err
}

const upsertDailyView = `-- name: UpsertDailyView :exec
INSERT INTO article_views_daily (article_id, day, views)
VALUES ($1, $2, 1)
ON CONFLICT (article_id, day) DO UPDATE SET views = article_views_daily.views + 1
`

type UpsertDailyViewParams struct {
	ArticleID int64     `json:"article_id"`
	Day       time.Time `json:"day"`
}

func (q *Queries) UpsertDailyView(ctx context.Context, arg UpsertDailyViewParams) error {
	_, err := q.db.Exec(ctx, upsertDailyView, arg.ArticleID, arg.Day)
	return err
}
