// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package dbgen

import (
	"context"
	"time"
)

const articleSlugExists = `-- name: ArticleSlugExists :one
SELECT EXISTS (
  SELECT 1 FROM articles WHERE slug = $1::text AND id <> $2::bigint
) AS exists
`

type ArticleSlugExistsParams struct {
	Slug      string `json:"slug"`
	ExcludeID int64  `json:"exclude_id"`
}

func (q *Queries) ArticleSlugExists(ctx context.Context, arg ArticleSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, articleSlugExists, arg.Slug, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countArticlesAdmin = `-- name: CountArticlesAdmin :one
SELECT count(*) FROM articles a
WHERE ($1::text IS NULL OR a.title ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR a.status = $2::text)
  AND ($3::bigint[] IS NULL OR a.category_id = ANY($3::bigint[]))
  AND ($4::bigint IS NULL OR a.author_id = $4::bigint)
  AND (($5::bool AND a.deleted_at IS NOT NULL)
       OR (NOT $5::bool AND a.deleted_at IS NULL))
`

type CountArticlesAdminParams struct {
	Q           *string `json:"q"`
	Status      *string `json:"status"`
	CategoryIds []int64 `json:"category_ids"`
	AuthorID    *int64  `json:"author_id"`
	Trashed     bool    `json:"trashed"`
}

func (q *Queries) CountArticlesAdmin(ctx context.Context, arg CountArticlesAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesAdmin,
		arg.Q,
		arg.Status,
		arg.CategoryIds,
		arg.AuthorID,
		arg.Trashed,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countArticlesByStatus = `-- name: CountArticlesByStatus :many
SELECT status, count(*)::bigint AS count
FROM articles
WHERE deleted_at IS NULL
GROUP BY status
ORDER BY status
`

type CountArticlesByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountArticlesByStatus(ctx context.Context) ([]CountArticlesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countArticlesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountArticlesByStatusRow{}
	for rows.Next() {
		var i CountArticlesByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPublishedArticles = `-- name: CountPublishedArticles :one
SELECT count(*) FROM articles a
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
  AND ($1::bigint[] IS NULL OR a.category_id = ANY($1::bigint[]))
  AND ($2::bigint IS NULL OR EXISTS (
        SELECT 1 FROM article_tags at WHERE at.article_id = a.id AND at.tag_id = $2::bigint))
  AND ($3::bigint IS NULL OR a.author_id = $3::bigint)
  AND ($4::bool IS NULL OR a.is_featured = $4::bool)
`

type CountPublishedArticlesParams struct {
	CategoryIds []int64 `json:"category_ids"`
	TagID       *int64  `json:"tag_id"`
	AuthorID    *int64  `json:"author_id"`
	Featured    *bool   `json:"featured"`
}

func (q *Queries) CountPublishedArticles(ctx context.Context, arg CountPublishedArticlesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedArticles,
		arg.CategoryIds,
		arg.TagID,
		arg.AuthorID,
		arg.Featured,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArticle = `-- name: CreateArticle :one

INSERT INTO articles (
  title, slug, excerpt, content_json, content_html, content_text,
  cover_media_id, cover_caption, category_id, author_id, status, published_at,
  is_featured, is_breaking, reading_minutes, event_date, event_location,
  seo_title, seo_description, og_media_id, canonical_url, created_by, updated_by)
VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11, $12,
  $13, $14, $15, $16, $17,
  $18, $19, $20, $21, $22, $23)
RETURNING id, title, slug, excerpt, content_json, content_html, content_text, cover_media_id, cover_caption, category_id, author_id, status, published_at, is_featured, is_breaking, reading_minutes, event_date, event_location, view_count, seo_title, seo_description, og_media_id, canonical_url, search_vector, created_by, updated_by, created_at, updated_at, deleted_at
`

type CreateArticleParams struct {
	Title          string     `json:"title"`
	Slug           string     `json:"slug"`
	Excerpt        *string    `json:"excerpt"`
	ContentJson    []byte     `json:"content_json"`
	ContentHtml    string     `json:"content_html"`
	ContentText    string     `json:"content_text"`
	CoverMediaID   *int64     `json:"cover_media_id"`
	CoverCaption   *string    `json:"cover_caption"`
	CategoryID     int64      `json:"category_id"`
	AuthorID       int64      `json:"author_id"`
	Status         string     `json:"status"`
	PublishedAt    *time.Time `json:"published_at"`
	IsFeatured     bool       `json:"is_featured"`
	IsBreaking     bool       `json:"is_breaking"`
	ReadingMinutes int16      `json:"reading_minutes"`
	EventDate      *time.Time `json:"event_date"`
	EventLocation  *string    `json:"event_location"`
	SeoTitle       *string    `json:"seo_title"`
	SeoDescription *string    `json:"seo_description"`
	OgMediaID      *int64     `json:"og_media_id"`
	CanonicalUrl   *string    `json:"canonical_url"`
	CreatedBy      *int64     `json:"created_by"`
	UpdatedBy      *int64     `json:"updated_by"`
}

// Public predicate used by every ListPublished*/GetPublished* query:
//
//	a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
//
// All article list queries select a.* so sqlc returns dbgen.Article; cards are
// hydrated in Go (internal/content.Hydrator).
func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, createArticle,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.ContentJson,
		arg.ContentHtml,
		arg.ContentText,
		arg.CoverMediaID,
		arg.CoverCaption,
		arg.CategoryID,
		arg.AuthorID,
		arg.Status,
		arg.PublishedAt,
		arg.IsFeatured,
		arg.IsBreaking,
		arg.ReadingMinutes,
		arg.EventDate,
		arg.EventLocation,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.OgMediaID,
		arg.CanonicalUrl,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.ContentJson,
		&i.ContentHtml,
		&i.ContentText,
		&i.CoverMediaID,
		&i.CoverCaption,
		&i.CategoryID,
		&i.AuthorID,
		&i.Status,
		&i.PublishedAt,
		&i.IsFeatured,
		&i.IsBreaking,
		&i.ReadingMinutes,
		&i.EventDate,
		&i.EventLocation,
		&i.ViewCount,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgMediaID,
		&i.CanonicalUrl,
		&i.SearchVector,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSlugRedirect = `-- name: DeleteSlugRedirect :exec
DELETE FROM article_slug_redirects WHERE old_slug = $1
`

func (q *Queries) DeleteSlugRedirect(ctx context.Context, oldSlug string) error {
	_, err := q.db.Exec(ctx, deleteSlugRedirect, oldSlug)
	return err
}

const getArticle = `-- name: GetArticle :one
SELECT id, title, slug, excerpt, content_json, content_html, content_text, cover_media_id, cover_caption, category_id, author_id, status, published_at, is_featured, is_breaking, reading_minutes, event_date, event_location, view_count, seo_title, seo_description, og_media_id, canonical_url, search_vector, created_by, updated_by, created_at, updated_at, deleted_at FROM articles WHERE id = $1
`

func (q *Queries) GetArticle(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRow(ctx, getArticle, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.ContentJson,
		&i.ContentHtml,
		&i.ContentText,
		&i.CoverMediaID,
		&i.CoverCaption,
		&i.CategoryID,
		&i.AuthorID,
		&i.Status,
		&i.PublishedAt,
		&i.IsFeatured,
		&i.IsBreaking,
		&i.ReadingMinutes,
		&i.EventDate,
		&i.EventLocation,
		&i.ViewCount,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgMediaID,
		&i.CanonicalUrl,
		&i.SearchVector,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getArticleBySlugAny = `-- name: GetArticleBySlugAny :one
SELECT id, title, slug, excerpt, content_json, content_html, content_text, cover_media_id, cover_caption, category_id, author_id, status, published_at, is_featured, is_breaking, reading_minutes, event_date, event_location, view_count, seo_title, seo_description, og_media_id, canonical_url, search_vector, created_by, updated_by, created_at, updated_at, deleted_at FROM articles WHERE slug = $1 AND deleted_at IS NULL
`

// GetArticleBySlugAny: any status, not deleted (preview).
func (q *Queries) GetArticleBySlugAny(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySlugAny, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.ContentJson,
		&i.ContentHtml,
		&i.ContentText,
		&i.CoverMediaID,
		&i.CoverCaption,
		&i.CategoryID,
		&i.AuthorID,
		&i.Status,
		&i.PublishedAt,
		&i.IsFeatured,
		&i.IsBreaking,
		&i.ReadingMinutes,
		&i.EventDate,
		&i.EventLocation,
		&i.ViewCount,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgMediaID,
		&i.CanonicalUrl,
		&i.SearchVector,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPublishedArticleBySlug = `-- name: GetPublishedArticleBySlug :one
SELECT a.id, a.title, a.slug, a.excerpt, a.content_json, a.content_html, a.content_text, a.cover_media_id, a.cover_caption, a.category_id, a.author_id, a.status, a.published_at, a.is_featured, a.is_breaking, a.reading_minutes, a.event_date, a.event_location, a.view_count, a.seo_title, a.seo_description, a.og_media_id, a.canonical_url, a.search_vector, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at FROM articles a
WHERE a.slug = $1
  AND a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
`

func (q *Queries) GetPublishedArticleBySlug(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRow(ctx, getPublishedArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.ContentJson,
		&i.ContentHtml,
		&i.ContentText,
		&i.CoverMediaID,
		&i.CoverCaption,
		&i.CategoryID,
		&i.AuthorID,
		&i.Status,
		&i.PublishedAt,
		&i.IsFeatured,
		&i.IsBreaking,
		&i.ReadingMinutes,
		&i.EventDate,
		&i.EventLocation,
		&i.ViewCount,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgMediaID,
		&i.CanonicalUrl,
		&i.SearchVector,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSlugRedirect = `-- name: GetSlugRedirect :one
SELECT old_slug, article_id, created_at FROM article_slug_redirects WHERE old_slug = $1
`

func (q *Queries) GetSlugRedirect(ctx context.Context, oldSlug string) (ArticleSlugRedirect, error) {
	row := q.db.QueryRow(ctx, getSlugRedirect, oldSlug)
	var i ArticleSlugRedirect
	err := row.Scan(&i.OldSlug, &i.ArticleID, &i.CreatedAt)
	return i, err
}

const incrementArticleViewCount = `-- name: IncrementArticleViewCount :exec
UPDATE articles SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementArticleViewCount(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementArticleViewCount, id)
	return err
}

const listArticlesAdmin = `-- name: ListArticlesAdmin :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content_json, a.content_html, a.content_text, a.cover_media_id, a.cover_caption, a.category_id, a.author_id, a.status, a.published_at, a.is_featured, a.is_breaking, a.reading_minutes, a.event_date, a.event_location, a.view_count, a.seo_title, a.seo_description, a.og_media_id, a.canonical_url, a.search_vector, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at FROM articles a
WHERE ($1::text IS NULL OR a.title ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR a.status = $2::text)
  AND ($3::bigint[] IS NULL OR a.category_id = ANY($3::bigint[]))
  AND ($4::bigint IS NULL OR a.author_id = $4::bigint)
  AND (($5::bool AND a.deleted_at IS NOT NULL)
       OR (NOT $5::bool AND a.deleted_at IS NULL))
ORDER BY
  CASE WHEN $6::text = 'title' THEN a.title END ASC,
  CASE WHEN $6::text = '-title' THEN a.title END DESC,
  CASE WHEN $6::text = 'published_at' THEN a.published_at END ASC NULLS LAST,
  CASE WHEN $6::text = '-published_at' THEN a.published_at END DESC NULLS LAST,
  CASE WHEN $6::text = '-view_count' THEN a.view_count END DESC,
  a.updated_at DESC, a.id DESC
LIMIT $8 OFFSET $7
`

type ListArticlesAdminParams struct {
	Q           *string `json:"q"`
	Status      *string `json:"status"`
	CategoryIds []int64 `json:"category_ids"`
	AuthorID    *int64  `json:"author_id"`
	Trashed     bool    `json:"trashed"`
	Sort        string  `json:"sort"`
	Offset      int32   `json:"offset"`
	Limit       int32   `json:"limit"`
}

// ListArticlesAdmin: sort whitelist '-updated_at' (default, any other value),
// '-published_at', 'published_at', 'title', '-title', '-view_count'.
func (q *Queries) ListArticlesAdmin(ctx context.Context, arg ListArticlesAdminParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticlesAdmin,
		arg.Q,
		arg.Status,
		arg.CategoryIds,
		arg.AuthorID,
		arg.Trashed,
		arg.Sort,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentJson,
			&i.ContentHtml,
			&i.ContentText,
			&i.CoverMediaID,
			&i.CoverCaption,
			&i.CategoryID,
			&i.AuthorID,
			&i.Status,
			&i.PublishedAt,
			&i.IsFeatured,
			&i.IsBreaking,
			&i.ReadingMinutes,
			&i.EventDate,
			&i.EventLocation,
			&i.ViewCount,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.OgMediaID,
			&i.CanonicalUrl,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBreakingPublished = `-- name: ListBreakingPublished :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content_json, a.content_html, a.content_text, a.cover_media_id, a.cover_caption, a.category_id, a.author_id, a.status, a.published_at, a.is_featured, a.is_breaking, a.reading_minutes, a.event_date, a.event_location, a.view_count, a.seo_title, a.seo_description, a.og_media_id, a.canonical_url, a.search_vector, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at FROM articles a
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
  AND a.is_breaking
ORDER BY a.published_at DESC, a.id DESC
LIMIT $1
`

func (q *Queries) ListBreakingPublished(ctx context.Context, limit int32) ([]Article, error) {
	rows, err := q.db.Query(ctx, listBreakingPublished, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentJson,
			&i.ContentHtml,
			&i.ContentText,
			&i.CoverMediaID,
			&i.CoverCaption,
			&i.CategoryID,
			&i.AuthorID,
			&i.Status,
			&i.PublishedAt,
			&i.IsFeatured,
			&i.IsBreaking,
			&i.ReadingMinutes,
			&i.EventDate,
			&i.EventLocation,
			&i.ViewCount,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.OgMediaID,
			&i.CanonicalUrl,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeaturedPublished = `-- name: ListFeaturedPublished :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content_json, a.content_html, a.content_text, a.cover_media_id, a.cover_caption, a.category_id, a.author_id, a.status, a.published_at, a.is_featured, a.is_breaking, a.reading_minutes, a.event_date, a.event_location, a.view_count, a.seo_title, a.seo_description, a.og_media_id, a.canonical_url, a.search_vector, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at FROM articles a
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
  AND a.is_featured
  AND ($1::bigint[] IS NULL OR a.category_id = ANY($1::bigint[]))
  AND NOT (a.id = ANY(COALESCE($2::bigint[], '{}'::bigint[])))
ORDER BY a.published_at DESC, a.id DESC
LIMIT $3
`

type ListFeaturedPublishedParams struct {
	CategoryIds []int64 `json:"category_ids"`
	ExcludeIds  []int64 `json:"exclude_ids"`
	Limit       int32   `json:"limit"`
}

func (q *Queries) ListFeaturedPublished(ctx context.Context, arg ListFeaturedPublishedParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listFeaturedPublished, arg.CategoryIds, arg.ExcludeIds, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentJson,
			&i.ContentHtml,
			&i.ContentText,
			&i.CoverMediaID,
			&i.CoverCaption,
			&i.CategoryID,
			&i.AuthorID,
			&i.Status,
			&i.PublishedAt,
			&i.IsFeatured,
			&i.IsBreaking,
			&i.ReadingMinutes,
			&i.EventDate,
			&i.EventLocation,
			&i.ViewCount,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.OgMediaID,
			&i.CanonicalUrl,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPublishedExcluding = `-- name: ListLatestPublishedExcluding :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content_json, a.content_html, a.content_text, a.cover_media_id, a.cover_caption, a.category_id, a.author_id, a.status, a.published_at, a.is_featured, a.is_breaking, a.reading_minutes, a.event_date, a.event_location, a.view_count, a.seo_title, a.seo_description, a.og_media_id, a.canonical_url, a.search_vector, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at FROM articles a
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
  AND NOT (a.id = ANY(COALESCE($1::bigint[], '{}'::bigint[])))
ORDER BY a.published_at DESC, a.id DESC
LIMIT $2
`

type ListLatestPublishedExcludingParams struct {
	ExcludeIds []int64 `json:"exclude_ids"`
	Limit      int32   `json:"limit"`
}

func (q *Queries) ListLatestPublishedExcluding(ctx context.Context, arg ListLatestPublishedExcludingParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listLatestPublishedExcluding, arg.ExcludeIds, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentJson,
			&i.ContentHtml,
			&i.ContentText,
			&i.CoverMediaID,
			&i.CoverCaption,
			&i.CategoryID,
			&i.AuthorID,
			&i.Status,
			&i.PublishedAt,
			&i.IsFeatured,
			&i.IsBreaking,
			&i.ReadingMinutes,
			&i.EventDate,
			&i.EventLocation,
			&i.ViewCount,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.OgMediaID,
			&i.CanonicalUrl,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticles = `-- name: ListPublishedArticles :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content_json, a.content_html, a.content_text, a.cover_media_id, a.cover_caption, a.category_id, a.author_id, a.status, a.published_at, a.is_featured, a.is_breaking, a.reading_minutes, a.event_date, a.event_location, a.view_count, a.seo_title, a.seo_description, a.og_media_id, a.canonical_url, a.search_vector, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at FROM articles a
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
  AND ($1::bigint[] IS NULL OR a.category_id = ANY($1::bigint[]))
  AND ($2::bigint IS NULL OR EXISTS (
        SELECT 1 FROM article_tags at WHERE at.article_id = a.id AND at.tag_id = $2::bigint))
  AND ($3::bigint IS NULL OR a.author_id = $3::bigint)
  AND ($4::bool IS NULL OR a.is_featured = $4::bool)
ORDER BY a.published_at DESC, a.id DESC
LIMIT $6 OFFSET $5
`

type ListPublishedArticlesParams struct {
	CategoryIds []int64 `json:"category_ids"`
	TagID       *int64  `json:"tag_id"`
	AuthorID    *int64  `json:"author_id"`
	Featured    *bool   `json:"featured"`
	Offset      int32   `json:"offset"`
	Limit       int32   `json:"limit"`
}

func (q *Queries) ListPublishedArticles(ctx context.Context, arg ListPublishedArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listPublishedArticles,
		arg.CategoryIds,
		arg.TagID,
		arg.AuthorID,
		arg.Featured,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentJson,
			&i.ContentHtml,
			&i.ContentText,
			&i.CoverMediaID,
			&i.CoverCaption,
			&i.CategoryID,
			&i.AuthorID,
			&i.Status,
			&i.PublishedAt,
			&i.IsFeatured,
			&i.IsBreaking,
			&i.ReadingMinutes,
			&i.EventDate,
			&i.EventLocation,
			&i.ViewCount,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.OgMediaID,
			&i.CanonicalUrl,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticlesByIDs = `-- name: ListPublishedArticlesByIDs :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content_json, a.content_html, a.content_text, a.cover_media_id, a.cover_caption, a.category_id, a.author_id, a.status, a.published_at, a.is_featured, a.is_breaking, a.reading_minutes, a.event_date, a.event_location, a.view_count, a.seo_title, a.seo_description, a.og_media_id, a.canonical_url, a.search_vector, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at FROM articles a
WHERE a.id = ANY($1::bigint[])
  AND a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
`

// ListPublishedArticlesByIDs: row order is arbitrary; callers restore their order.
func (q *Queries) ListPublishedArticlesByIDs(ctx context.Context, ids []int64) ([]Article, error) {
	rows, err := q.db.Query(ctx, listPublishedArticlesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentJson,
			&i.ContentHtml,
			&i.ContentText,
			&i.CoverMediaID,
			&i.CoverCaption,
			&i.CategoryID,
			&i.AuthorID,
			&i.Status,
			&i.PublishedAt,
			&i.IsFeatured,
			&i.IsBreaking,
			&i.ReadingMinutes,
			&i.EventDate,
			&i.EventLocation,
			&i.ViewCount,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.OgMediaID,
			&i.CanonicalUrl,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedArticlesForSitemap = `-- name: ListPublishedArticlesForSitemap :many
SELECT a.id, a.slug, a.category_id, a.updated_at
FROM articles a
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
ORDER BY a.published_at DESC, a.id DESC
`

type ListPublishedArticlesForSitemapRow struct {
	ID         int64     `json:"id"`
	Slug       string    `json:"slug"`
	CategoryID int64     `json:"category_id"`
	UpdatedAt  time.Time `json:"updated_at"`
}

func (q *Queries) ListPublishedArticlesForSitemap(ctx context.Context) ([]ListPublishedArticlesForSitemapRow, error) {
	rows, err := q.db.Query(ctx, listPublishedArticlesForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedArticlesForSitemapRow{}
	for rows.Next() {
		var i ListPublishedArticlesForSitemapRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.CategoryID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedByCategoryOrdered = `-- name: ListPublishedByCategoryOrdered :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content_json, a.content_html, a.content_text, a.cover_media_id, a.cover_caption, a.category_id, a.author_id, a.status, a.published_at, a.is_featured, a.is_breaking, a.reading_minutes, a.event_date, a.event_location, a.view_count, a.seo_title, a.seo_description, a.og_media_id, a.canonical_url, a.search_vector, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at FROM articles a
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
  AND ($1::bigint[] IS NULL OR a.category_id = ANY($1::bigint[]))
  AND ($2::bigint IS NULL OR EXISTS (
        SELECT 1 FROM article_tags at WHERE at.article_id = a.id AND at.tag_id = $2::bigint))
  AND NOT (a.id = ANY(COALESCE($3::bigint[], '{}'::bigint[])))
ORDER BY
  CASE WHEN $4::text = 'event_date' THEN a.event_date END DESC NULLS LAST,
  a.published_at DESC, a.id DESC
LIMIT $5
`

type ListPublishedByCategoryOrderedParams struct {
	CategoryIds []int64 `json:"category_ids"`
	TagID       *int64  `json:"tag_id"`
	ExcludeIds  []int64 `json:"exclude_ids"`
	OrderBy     string  `json:"order_by"`
	Limit       int32   `json:"limit"`
}

// ListPublishedByCategoryOrdered: category_ids/tag_id NULL = no filter;
// order_by 'event_date' (event_date DESC NULLS LAST, then published_at) or anything
// else = 'published_at'.
func (q *Queries) ListPublishedByCategoryOrdered(ctx context.Context, arg ListPublishedByCategoryOrderedParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listPublishedByCategoryOrdered,
		arg.CategoryIds,
		arg.TagID,
		arg.ExcludeIds,
		arg.OrderBy,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentJson,
			&i.ContentHtml,
			&i.ContentText,
			&i.CoverMediaID,
			&i.CoverCaption,
			&i.CategoryID,
			&i.AuthorID,
			&i.Status,
			&i.PublishedAt,
			&i.IsFeatured,
			&i.IsBreaking,
			&i.ReadingMinutes,
			&i.EventDate,
			&i.EventLocation,
			&i.ViewCount,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.OgMediaID,
			&i.CanonicalUrl,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDrafts = `-- name: ListRecentDrafts :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content_json, a.content_html, a.content_text, a.cover_media_id, a.cover_caption, a.category_id, a.author_id, a.status, a.published_at, a.is_featured, a.is_breaking, a.reading_minutes, a.event_date, a.event_location, a.view_count, a.seo_title, a.seo_description, a.og_media_id, a.canonical_url, a.search_vector, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at FROM articles a
WHERE a.status IN ('draft', 'scheduled') AND a.deleted_at IS NULL
ORDER BY a.updated_at DESC, a.id DESC
LIMIT $1
`

func (q *Queries) ListRecentDrafts(ctx context.Context, limit int32) ([]Article, error) {
	rows, err := q.db.Query(ctx, listRecentDrafts, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentJson,
			&i.ContentHtml,
			&i.ContentText,
			&i.CoverMediaID,
			&i.CoverCaption,
			&i.CategoryID,
			&i.AuthorID,
			&i.Status,
			&i.PublishedAt,
			&i.IsFeatured,
			&i.IsBreaking,
			&i.ReadingMinutes,
			&i.EventDate,
			&i.EventLocation,
			&i.ViewCount,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.OgMediaID,
			&i.CanonicalUrl,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelatedArticles = `-- name: ListRelatedArticles :many
SELECT a.id, a.title, a.slug, a.excerpt, a.content_json, a.content_html, a.content_text, a.cover_media_id, a.cover_caption, a.category_id, a.author_id, a.status, a.published_at, a.is_featured, a.is_breaking, a.reading_minutes, a.event_date, a.event_location, a.view_count, a.seo_title, a.seo_description, a.og_media_id, a.canonical_url, a.search_vector, a.created_by, a.updated_by, a.created_at, a.updated_at, a.deleted_at FROM articles a
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
  AND a.id <> $1::bigint
  AND (a.category_id = $2::bigint OR EXISTS (
        SELECT 1 FROM article_tags t1 JOIN article_tags t2 ON t2.tag_id = t1.tag_id
        WHERE t1.article_id = a.id AND t2.article_id = $1::bigint))
ORDER BY
  (a.category_id = $2::bigint)::int DESC,
  (SELECT count(*) FROM article_tags t1 JOIN article_tags t2 ON t2.tag_id = t1.tag_id
   WHERE t1.article_id = a.id AND t2.article_id = $1::bigint) DESC,
  a.published_at DESC, a.id DESC
LIMIT $3
`

type ListRelatedArticlesParams struct {
	ArticleID  int64 `json:"article_id"`
	CategoryID int64 `json:"category_id"`
	Limit      int32 `json:"limit"`
}

// ListRelatedArticles: published articles (not article_id) in the same category
// or sharing a tag; same category first, then shared-tag count, then recency.
func (q *Queries) ListRelatedArticles(ctx context.Context, arg ListRelatedArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listRelatedArticles, arg.ArticleID, arg.CategoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Excerpt,
			&i.ContentJson,
			&i.ContentHtml,
			&i.ContentText,
			&i.CoverMediaID,
			&i.CoverCaption,
			&i.CategoryID,
			&i.AuthorID,
			&i.Status,
			&i.PublishedAt,
			&i.IsFeatured,
			&i.IsBreaking,
			&i.ReadingMinutes,
			&i.EventDate,
			&i.EventLocation,
			&i.ViewCount,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.OgMediaID,
			&i.CanonicalUrl,
			&i.SearchVector,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishDueArticles = `-- name: PublishDueArticles :many
UPDATE articles
SET status = 'published'
WHERE status = 'scheduled' AND published_at <= now() AND deleted_at IS NULL
RETURNING id, slug, category_id, author_id
`

type PublishDueArticlesRow struct {
	ID         int64  `json:"id"`
	Slug       string `json:"slug"`
	CategoryID int64  `json:"category_id"`
	AuthorID   int64  `json:"author_id"`
}

func (q *Queries) PublishDueArticles(ctx context.Context) ([]PublishDueArticlesRow, error) {
	rows, err := q.db.Query(ctx, publishDueArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublishDueArticlesRow{}
	for rows.Next() {
		var i PublishDueArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.CategoryID,
			&i.AuthorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreArticle = `-- name: RestoreArticle :execrows
UPDATE articles SET deleted_at = NULL WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreArticle(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, restoreArticle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setArticleStatus = `-- name: SetArticleStatus :one
UPDATE articles
SET status = $1,
    published_at = COALESCE($2::timestamptz, published_at),
    updated_by = $3
WHERE id = $4
RETURNING id, title, slug, excerpt, content_json, content_html, content_text, cover_media_id, cover_caption, category_id, author_id, status, published_at, is_featured, is_breaking, reading_minutes, event_date, event_location, view_count, seo_title, seo_description, og_media_id, canonical_url, search_vector, created_by, updated_by, created_at, updated_at, deleted_at
`

type SetArticleStatusParams struct {
	Status      string     `json:"status"`
	PublishedAt *time.Time `json:"published_at"`
	UpdatedBy   *int64     `json:"updated_by"`
	ID          int64      `json:"id"`
}

// SetArticleStatus: published_at NULL keeps the stored value (unpublish keeps it).
func (q *Queries) SetArticleStatus(ctx context.Context, arg SetArticleStatusParams) (Article, error) {
	row := q.db.QueryRow(ctx, setArticleStatus,
		arg.Status,
		arg.PublishedAt,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.ContentJson,
		&i.ContentHtml,
		&i.ContentText,
		&i.CoverMediaID,
		&i.CoverCaption,
		&i.CategoryID,
		&i.AuthorID,
		&i.Status,
		&i.PublishedAt,
		&i.IsFeatured,
		&i.IsBreaking,
		&i.ReadingMinutes,
		&i.EventDate,
		&i.EventLocation,
		&i.ViewCount,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgMediaID,
		&i.CanonicalUrl,
		&i.SearchVector,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteArticle = `-- name: SoftDeleteArticle :execrows
UPDATE articles SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteArticle(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteArticle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateArticle = `-- name: UpdateArticle :one
UPDATE articles
SET title = $1,
    slug = $2,
    excerpt = $3,
    content_json = $4,
    content_html = $5,
    content_text = $6,
    cover_media_id = $7,
    cover_caption = $8,
    category_id = $9,
    author_id = $10,
    is_featured = $11,
    is_breaking = $12,
    reading_minutes = $13,
    event_date = $14,
    event_location = $15,
    seo_title = $16,
    seo_description = $17,
    og_media_id = $18,
    canonical_url = $19,
    updated_by = $20
WHERE id = $21
RETURNING id, title, slug, excerpt, content_json, content_html, content_text, cover_media_id, cover_caption, category_id, author_id, status, published_at, is_featured, is_breaking, reading_minutes, event_date, event_location, view_count, seo_title, seo_description, og_media_id, canonical_url, search_vector, created_by, updated_by, created_at, updated_at, deleted_at
`

type UpdateArticleParams struct {
	Title          string     `json:"title"`
	Slug           string     `json:"slug"`
	Excerpt        *string    `json:"excerpt"`
	ContentJson    []byte     `json:"content_json"`
	ContentHtml    string     `json:"content_html"`
	ContentText    string     `json:"content_text"`
	CoverMediaID   *int64     `json:"cover_media_id"`
	CoverCaption   *string    `json:"cover_caption"`
	CategoryID     int64      `json:"category_id"`
	AuthorID       int64      `json:"author_id"`
	IsFeatured     bool       `json:"is_featured"`
	IsBreaking     bool       `json:"is_breaking"`
	ReadingMinutes int16      `json:"reading_minutes"`
	EventDate      *time.Time `json:"event_date"`
	EventLocation  *string    `json:"event_location"`
	SeoTitle       *string    `json:"seo_title"`
	SeoDescription *string    `json:"seo_description"`
	OgMediaID      *int64     `json:"og_media_id"`
	CanonicalUrl   *string    `json:"canonical_url"`
	UpdatedBy      *int64     `json:"updated_by"`
	ID             int64      `json:"id"`
}

// UpdateArticle updates editable columns; status/published_at go through SetArticleStatus.
func (q *Queries) UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error) {
	row := q.db.QueryRow(ctx, updateArticle,
		arg.Title,
		arg.Slug,
		arg.Excerpt,
		arg.ContentJson,
		arg.ContentHtml,
		arg.ContentText,
		arg.CoverMediaID,
		arg.CoverCaption,
		arg.CategoryID,
		arg.AuthorID,
		arg.IsFeatured,
		arg.IsBreaking,
		arg.ReadingMinutes,
		arg.EventDate,
		arg.EventLocation,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.OgMediaID,
		arg.CanonicalUrl,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Excerpt,
		&i.ContentJson,
		&i.ContentHtml,
		&i.ContentText,
		&i.CoverMediaID,
		&i.CoverCaption,
		&i.CategoryID,
		&i.AuthorID,
		&i.Status,
		&i.PublishedAt,
		&i.IsFeatured,
		&i.IsBreaking,
		&i.ReadingMinutes,
		&i.EventDate,
		&i.EventLocation,
		&i.ViewCount,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgMediaID,
		&i.CanonicalUrl,
		&i.SearchVector,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertSlugRedirect = `-- name: UpsertSlugRedirect :exec
INSERT INTO article_slug_redirects (old_slug, article_id)
VALUES ($1, $2)
ON CONFLICT (old_slug) DO UPDATE SET article_id = EXCLUDED.article_id, created_at = now()
`

type UpsertSlugRedirectParams struct {
	OldSlug   string `json:"old_slug"`
	ArticleID int64  `json:"article_id"`
}

func (q *Queries) UpsertSlugRedirect(ctx context.Context, arg UpsertSlugRedirectParams) error {
	_, err := q.db.Exec(ctx, upsertSlugRedirect, arg.OldSlug, arg.ArticleID)
	return err
}
