// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*)
FROM audit_logs a
WHERE ($1::text IS NULL OR a.entity_type = $1::text)
  AND ($2::bigint IS NULL OR a.user_id = $2::bigint)
  AND ($3::text IS NULL OR a.action = $3::text)
  AND ($4::timestamptz IS NULL OR a.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR a.created_at < $5::timestamptz)
`

type CountAuditLogsParams struct {
	EntityType *string    `json:"entity_type"`
	UserID     *int64     `json:"user_id"`
	Action     *string    `json:"action"`
	From       *time.Time `json:"from"`
	To         *time.Time `json:"to"`
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.EntityType,
		arg.UserID,
		arg.Action,
		arg.From,
		arg.To,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (user_id, action, entity_type, entity_id, summary, changes, ip)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
`

type InsertAuditLogParams struct {
	UserID     *int64      `json:"user_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   *int64      `json:"entity_id"`
	Summary    string      `json:"summary"`
	Changes    []byte      `json:"changes"`
	Ip         *netip.Addr `json:"ip"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Summary,
		arg.Changes,
		arg.Ip,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.user_id, u.display_name AS user_display_name, a.action, a.entity_type,
       a.entity_id, a.summary, a.changes, a.ip, a.created_at
FROM audit_logs a
LEFT JOIN users u ON u.id = a.user_id
WHERE ($1::text IS NULL OR a.entity_type = $1::text)
  AND ($2::bigint IS NULL OR a.user_id = $2::bigint)
  AND ($3::text IS NULL OR a.action = $3::text)
  AND ($4::timestamptz IS NULL OR a.created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR a.created_at < $5::timestamptz)
ORDER BY a.created_at DESC, a.id DESC
LIMIT $7 OFFSET $6
`

type ListAuditLogsParams struct {
	EntityType *string    `json:"entity_type"`
	UserID     *int64     `json:"user_id"`
	Action     *string    `json:"action"`
	From       *time.Time `json:"from"`
	To         *time.Time `json:"to"`
	Offset     int32      `json:"offset"`
	Limit      int32      `json:"limit"`
}

type ListAuditLogsRow struct {
	ID              int64       `json:"id"`
	UserID          *int64      `json:"user_id"`
	UserDisplayName *string     `json:"user_display_name"`
	Action          string      `json:"action"`
	EntityType      string      `json:"entity_type"`
	EntityID        *int64      `json:"entity_id"`
	Summary         string      `json:"summary"`
	Changes         []byte      `json:"changes"`
	Ip              *netip.Addr `json:"ip"`
	CreatedAt       time.Time   `json:"created_at"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.EntityType,
		arg.UserID,
		arg.Action,
		arg.From,
		arg.To,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogsRow{}
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserDisplayName,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Summary,
			&i.Changes,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
