// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, family_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, COALESCE($2::uuid, gen_random_uuid()),
        $3, $4, $5, $6)
RETURNING id, family_id, expires_at
`

type CreateRefreshTokenParams struct {
	UserID    int64       `json:"user_id"`
	FamilyID  pgtype.UUID `json:"family_id"`
	TokenHash []byte      `json:"token_hash"`
	ExpiresAt time.Time   `json:"expires_at"`
	UserAgent *string     `json:"user_agent"`
	Ip        *netip.Addr `json:"ip"`
}

type CreateRefreshTokenRow struct {
	ID        int64       `json:"id"`
	FamilyID  pgtype.UUID `json:"family_id"`
	ExpiresAt time.Time   `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (CreateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i CreateRefreshTokenRow
	err := row.Scan(&i.ID, &i.FamilyID, &i.ExpiresAt)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE FROM refresh_tokens WHERE expires_at < now() - interval '30 days'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRefreshTokenByHashForUpdate = `-- name: GetRefreshTokenByHashForUpdate :one
SELECT rt.id, rt.user_id, rt.family_id, rt.expires_at, rt.rotated_at, rt.revoked_at,
       u.is_active, u.can_login, u.perm_version
FROM refresh_tokens rt
JOIN users u ON u.id = rt.user_id
WHERE rt.token_hash = $1
FOR UPDATE OF rt
`

type GetRefreshTokenByHashForUpdateRow struct {
	ID          int64       `json:"id"`
	UserID      int64       `json:"user_id"`
	FamilyID    pgtype.UUID `json:"family_id"`
	ExpiresAt   time.Time   `json:"expires_at"`
	RotatedAt   *time.Time  `json:"rotated_at"`
	RevokedAt   *time.Time  `json:"revoked_at"`
	IsActive    bool        `json:"is_active"`
	CanLogin    bool        `json:"can_login"`
	PermVersion int32       `json:"perm_version"`
}

func (q *Queries) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (GetRefreshTokenByHashForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHashForUpdate, tokenHash)
	var i GetRefreshTokenByHashForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.ExpiresAt,
		&i.RotatedAt,
		&i.RevokedAt,
		&i.IsActive,
		&i.CanLogin,
		&i.PermVersion,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT rt.family_id, rt.user_agent, rt.ip,
       (SELECT min(f.created_at) FROM refresh_tokens f WHERE f.family_id = rt.family_id)::timestamptz AS started_at,
       rt.created_at AS last_used_at,
       rt.expires_at
FROM refresh_tokens rt
WHERE rt.user_id = $1
  AND rt.revoked_at IS NULL
  AND rt.rotated_at IS NULL
  AND rt.expires_at > now()
ORDER BY rt.created_at DESC
`

type ListActiveSessionsRow struct {
	FamilyID   pgtype.UUID `json:"family_id"`
	UserAgent  *string     `json:"user_agent"`
	Ip         *netip.Addr `json:"ip"`
	StartedAt  time.Time   `json:"started_at"`
	LastUsedAt time.Time   `json:"last_used_at"`
	ExpiresAt  time.Time   `json:"expires_at"`
}

func (q *Queries) ListActiveSessions(ctx context.Context, userID int64) ([]ListActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSessionsRow{}
	for rows.Next() {
		var i ListActiveSessionsRow
		if err := rows.Scan(
			&i.FamilyID,
			&i.UserAgent,
			&i.Ip,
			&i.StartedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshTokenRotated = `-- name: MarkRefreshTokenRotated :exec
UPDATE refresh_tokens SET rotated_at = now() WHERE id = $1
`

func (q *Queries) MarkRefreshTokenRotated(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRefreshTokenRotated, id)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :execrows
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeOtherUserRefreshTokens = `-- name: RevokeOtherUserRefreshTokens :execrows
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND family_id <> $2 AND revoked_at IS NULL
`

type RevokeOtherUserRefreshTokensParams struct {
	UserID       int64       `json:"user_id"`
	KeepFamilyID pgtype.UUID `json:"keep_family_id"`
}

func (q *Queries) RevokeOtherUserRefreshTokens(ctx context.Context, arg RevokeOtherUserRefreshTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOtherUserRefreshTokens, arg.UserID, arg.KeepFamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :execrows
UPDATE refresh_tokens SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, familyID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenFamily, familyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserRefreshTokenFamily = `-- name: RevokeUserRefreshTokenFamily :execrows
UPDATE refresh_tokens SET revoked_at = now()
WHERE family_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeUserRefreshTokenFamilyParams struct {
	FamilyID pgtype.UUID `json:"family_id"`
	UserID   int64       `json:"user_id"`
}

func (q *Queries) RevokeUserRefreshTokenFamily(ctx context.Context, arg RevokeUserRefreshTokenFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserRefreshTokenFamily, arg.FamilyID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
