// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package dbgen

import (
	"context"
	"time"
)

const countArticlesInCategory = `-- name: CountArticlesInCategory :one
SELECT count(*) FROM articles WHERE category_id = $1
`

// CountArticlesInCategory counts all rows, including drafts and soft-deleted.
func (q *Queries) CountArticlesInCategory(ctx context.Context, categoryID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countArticlesInCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCategoryChildren = `-- name: CountCategoryChildren :one
SELECT count(*) FROM categories WHERE parent_id = $1::bigint
`

func (q *Queries) CountCategoryChildren(ctx context.Context, parentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCategoryChildren, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (parent_id, name, slug, description, sort_order, is_active, seo_title, seo_description)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
RETURNING id, parent_id, name, slug, description, sort_order, is_active, seo_title, seo_description, created_at, updated_at
`

type CreateCategoryParams struct {
	ParentID       *int64  `json:"parent_id"`
	Name           string  `json:"name"`
	Slug           string  `json:"slug"`
	Description    *string `json:"description"`
	SortOrder      int32   `json:"sort_order"`
	IsActive       bool    `json:"is_active"`
	SeoTitle       *string `json:"seo_title"`
	SeoDescription *string `json:"seo_description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
		arg.IsActive,
		arg.SeoTitle,
		arg.SeoDescription,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, parent_id, name, slug, description, sort_order, is_active, seo_title, seo_description, created_at, updated_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, parent_id, name, slug, description, sort_order, is_active, seo_title, seo_description, created_at, updated_at FROM categories WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, parent_id, name, slug, description, sort_order, is_active, seo_title, seo_description, created_at, updated_at FROM categories
ORDER BY parent_id NULLS FIRST, sort_order, id
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.SortOrder,
			&i.IsActive,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithCounts = `-- name: ListCategoriesWithCounts :many
SELECT c.id, c.parent_id, c.name, c.slug, c.description, c.sort_order, c.is_active, c.seo_title, c.seo_description, c.created_at, c.updated_at,
       (SELECT count(*) FROM articles a
        WHERE a.category_id = c.id
          AND a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL)::bigint AS article_count
FROM categories c
ORDER BY c.parent_id NULLS FIRST, c.sort_order, c.id
`

type ListCategoriesWithCountsRow struct {
	ID             int64     `json:"id"`
	ParentID       *int64    `json:"parent_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    *string   `json:"description"`
	SortOrder      int32     `json:"sort_order"`
	IsActive       bool      `json:"is_active"`
	SeoTitle       *string   `json:"seo_title"`
	SeoDescription *string   `json:"seo_description"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	ArticleCount   int64     `json:"article_count"`
}

// ListCategoriesWithCounts: article_count counts published articles directly in c
// (children are aggregated in Go).
func (q *Queries) ListCategoriesWithCounts(ctx context.Context) ([]ListCategoriesWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listCategoriesWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesWithCountsRow{}
	for rows.Next() {
		var i ListCategoriesWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.SortOrder,
			&i.IsActive,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET parent_id = $1,
    name = $2,
    slug = $3,
    description = $4,
    sort_order = $5,
    is_active = $6,
    seo_title = $7,
    seo_description = $8
WHERE id = $9
RETURNING id, parent_id, name, slug, description, sort_order, is_active, seo_title, seo_description, created_at, updated_at
`

type UpdateCategoryParams struct {
	ParentID       *int64  `json:"parent_id"`
	Name           string  `json:"name"`
	Slug           string  `json:"slug"`
	Description    *string `json:"description"`
	SortOrder      int32   `json:"sort_order"`
	IsActive       bool    `json:"is_active"`
	SeoTitle       *string `json:"seo_title"`
	SeoDescription *string `json:"seo_description"`
	ID             int64   `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
		arg.IsActive,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCategoryOrder = `-- name: UpdateCategoryOrder :exec
UPDATE categories SET parent_id = $1, sort_order = $2
WHERE id = $3
`

type UpdateCategoryOrderParams struct {
	ParentID  *int64 `json:"parent_id"`
	SortOrder int32  `json:"sort_order"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateCategoryOrder(ctx context.Context, arg UpdateCategoryOrderParams) error {
	_, err := q.db.Exec(ctx, updateCategoryOrder, arg.ParentID, arg.SortOrder, arg.ID)
	return err
}
