// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package dbgen

import (
	"context"
	"time"
)

const countEventsAdmin = `-- name: CountEventsAdmin :one
SELECT count(*) FROM events
WHERE ($1::text IS NULL OR title ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR status = $2::text)
`

type CountEventsAdminParams struct {
	Q      *string `json:"q"`
	Status *string `json:"status"`
}

func (q *Queries) CountEventsAdmin(ctx context.Context, arg CountEventsAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsAdmin, arg.Q, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedEvents = `-- name: CountPublishedEvents :one
SELECT count(*) FROM events
WHERE status = 'published'
  AND ($1::text <> 'upcoming' OR COALESCE(ends_at, starts_at) >= now())
  AND ($1::text <> 'past' OR COALESCE(ends_at, starts_at) < now())
  AND ($2::timestamptz IS NULL OR starts_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR starts_at < $3::timestamptz)
`

type CountPublishedEventsParams struct {
	When      string     `json:"when"`
	MonthFrom *time.Time `json:"month_from"`
	MonthTo   *time.Time `json:"month_to"`
}

func (q *Queries) CountPublishedEvents(ctx context.Context, arg CountPublishedEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedEvents, arg.When, arg.MonthFrom, arg.MonthTo)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (
  title, slug, summary, description_json, description_html, starts_at, ends_at, is_all_day,
  location_name, location_address, maps_url, cover_media_id, registration_url, status,
  seo_title, seo_description, created_by, updated_by)
VALUES (
  $1, $2, $3, $4, $5,
  $6, $7, $8,
  $9, $10, $11, $12,
  $13, $14,
  $15, $16, $17, $18)
RETURNING id, title, slug, summary, description_json, description_html, starts_at, ends_at, is_all_day, location_name, location_address, maps_url, cover_media_id, registration_url, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at
`

type CreateEventParams struct {
	Title           string     `json:"title"`
	Slug            string     `json:"slug"`
	Summary         *string    `json:"summary"`
	DescriptionJson []byte     `json:"description_json"`
	DescriptionHtml *string    `json:"description_html"`
	StartsAt        time.Time  `json:"starts_at"`
	EndsAt          *time.Time `json:"ends_at"`
	IsAllDay        bool       `json:"is_all_day"`
	LocationName    string     `json:"location_name"`
	LocationAddress *string    `json:"location_address"`
	MapsUrl         *string    `json:"maps_url"`
	CoverMediaID    *int64     `json:"cover_media_id"`
	RegistrationUrl *string    `json:"registration_url"`
	Status          string     `json:"status"`
	SeoTitle        *string    `json:"seo_title"`
	SeoDescription  *string    `json:"seo_description"`
	CreatedBy       *int64     `json:"created_by"`
	UpdatedBy       *int64     `json:"updated_by"`
}

// Public event queries require status = 'published' (cancelled/draft are hidden).
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.DescriptionJson,
		arg.DescriptionHtml,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsAllDay,
		arg.LocationName,
		arg.LocationAddress,
		arg.MapsUrl,
		arg.CoverMediaID,
		arg.RegistrationUrl,
		arg.Status,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsAllDay,
		&i.LocationName,
		&i.LocationAddress,
		&i.MapsUrl,
		&i.CoverMediaID,
		&i.RegistrationUrl,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :execrows
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEvent, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const eventSlugExists = `-- name: EventSlugExists :one
SELECT EXISTS (
  SELECT 1 FROM events WHERE slug = $1::text AND id <> $2::bigint
) AS exists
`

type EventSlugExistsParams struct {
	Slug      string `json:"slug"`
	ExcludeID int64  `json:"exclude_id"`
}

func (q *Queries) EventSlugExists(ctx context.Context, arg EventSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, eventSlugExists, arg.Slug, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, title, slug, summary, description_json, description_html, starts_at, ends_at, is_all_day, location_name, location_address, maps_url, cover_media_id, registration_url, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsAllDay,
		&i.LocationName,
		&i.LocationAddress,
		&i.MapsUrl,
		&i.CoverMediaID,
		&i.RegistrationUrl,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventBySlug = `-- name: GetEventBySlug :one
SELECT id, title, slug, summary, description_json, description_html, starts_at, ends_at, is_all_day, location_name, location_address, maps_url, cover_media_id, registration_url, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM events WHERE slug = $1
`

func (q *Queries) GetEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsAllDay,
		&i.LocationName,
		&i.LocationAddress,
		&i.MapsUrl,
		&i.CoverMediaID,
		&i.RegistrationUrl,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedEventBySlug = `-- name: GetPublishedEventBySlug :one
SELECT id, title, slug, summary, description_json, description_html, starts_at, ends_at, is_all_day, location_name, location_address, maps_url, cover_media_id, registration_url, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM events WHERE slug = $1 AND status = 'published'
`

func (q *Queries) GetPublishedEventBySlug(ctx context.Context, slug string) (Event, error) {
	row := q.db.QueryRow(ctx, getPublishedEventBySlug, slug)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsAllDay,
		&i.LocationName,
		&i.LocationAddress,
		&i.MapsUrl,
		&i.CoverMediaID,
		&i.RegistrationUrl,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsAdmin = `-- name: ListEventsAdmin :many
SELECT id, title, slug, summary, description_json, description_html, starts_at, ends_at, is_all_day, location_name, location_address, maps_url, cover_media_id, registration_url, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM events
WHERE ($1::text IS NULL OR title ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY starts_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListEventsAdminParams struct {
	Q      *string `json:"q"`
	Status *string `json:"status"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) ListEventsAdmin(ctx context.Context, arg ListEventsAdminParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsAdmin,
		arg.Q,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.DescriptionJson,
			&i.DescriptionHtml,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsAllDay,
			&i.LocationName,
			&i.LocationAddress,
			&i.MapsUrl,
			&i.CoverMediaID,
			&i.RegistrationUrl,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEvents = `-- name: ListPublishedEvents :many
SELECT id, title, slug, summary, description_json, description_html, starts_at, ends_at, is_all_day, location_name, location_address, maps_url, cover_media_id, registration_url, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM events
WHERE status = 'published'
  AND ($1::text <> 'upcoming' OR COALESCE(ends_at, starts_at) >= now())
  AND ($1::text <> 'past' OR COALESCE(ends_at, starts_at) < now())
  AND ($2::timestamptz IS NULL OR starts_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR starts_at < $3::timestamptz)
ORDER BY
  CASE WHEN $1::text = 'past' THEN starts_at END DESC,
  starts_at ASC, id ASC
LIMIT $5 OFFSET $4
`

type ListPublishedEventsParams struct {
	When      string     `json:"when"`
	MonthFrom *time.Time `json:"month_from"`
	MonthTo   *time.Time `json:"month_to"`
	Offset    int32      `json:"offset"`
	Limit     int32      `json:"limit"`
}

// ListPublishedEvents: when = 'upcoming' (COALESCE(ends_at, starts_at) >= now(),
// starts_at ASC), 'past' (< now(), starts_at DESC), anything else = no time
// filter (starts_at ASC). month_from/month_to (NULL = open) filter starts_at in
// [month_from, month_to).
func (q *Queries) ListPublishedEvents(ctx context.Context, arg ListPublishedEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listPublishedEvents,
		arg.When,
		arg.MonthFrom,
		arg.MonthTo,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.DescriptionJson,
			&i.DescriptionHtml,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsAllDay,
			&i.LocationName,
			&i.LocationAddress,
			&i.MapsUrl,
			&i.CoverMediaID,
			&i.RegistrationUrl,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEventsBetween = `-- name: ListPublishedEventsBetween :many
SELECT id, title, slug, summary, description_json, description_html, starts_at, ends_at, is_all_day, location_name, location_address, maps_url, cover_media_id, registration_url, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM events
WHERE status = 'published'
  AND starts_at >= $1::timestamptz AND starts_at < $2::timestamptz
ORDER BY starts_at ASC, id ASC
`

type ListPublishedEventsBetweenParams struct {
	FromTs time.Time `json:"from_ts"`
	ToTs   time.Time `json:"to_ts"`
}

// ListPublishedEventsBetween: starts_at in [from_ts, to_ts) (calendar).
func (q *Queries) ListPublishedEventsBetween(ctx context.Context, arg ListPublishedEventsBetweenParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listPublishedEventsBetween, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.DescriptionJson,
			&i.DescriptionHtml,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsAllDay,
			&i.LocationName,
			&i.LocationAddress,
			&i.MapsUrl,
			&i.CoverMediaID,
			&i.RegistrationUrl,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedEventsForSitemap = `-- name: ListPublishedEventsForSitemap :many
SELECT slug, updated_at FROM events
WHERE status = 'published'
ORDER BY starts_at DESC, id DESC
`

type ListPublishedEventsForSitemapRow struct {
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListPublishedEventsForSitemap(ctx context.Context) ([]ListPublishedEventsForSitemapRow, error) {
	rows, err := q.db.Query(ctx, listPublishedEventsForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedEventsForSitemapRow{}
	for rows.Next() {
		var i ListPublishedEventsForSitemapRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingEvents = `-- name: ListUpcomingEvents :many
SELECT id, title, slug, summary, description_json, description_html, starts_at, ends_at, is_all_day, location_name, location_address, maps_url, cover_media_id, registration_url, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at FROM events
WHERE status = 'published' AND COALESCE(ends_at, starts_at) >= now()
ORDER BY starts_at ASC, id ASC
LIMIT $1
`

func (q *Queries) ListUpcomingEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUpcomingEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Summary,
			&i.DescriptionJson,
			&i.DescriptionHtml,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsAllDay,
			&i.LocationName,
			&i.LocationAddress,
			&i.MapsUrl,
			&i.CoverMediaID,
			&i.RegistrationUrl,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $1,
    slug = $2,
    summary = $3,
    description_json = $4,
    description_html = $5,
    starts_at = $6,
    ends_at = $7,
    is_all_day = $8,
    location_name = $9,
    location_address = $10,
    maps_url = $11,
    cover_media_id = $12,
    registration_url = $13,
    status = $14,
    seo_title = $15,
    seo_description = $16,
    updated_by = $17
WHERE id = $18
RETURNING id, title, slug, summary, description_json, description_html, starts_at, ends_at, is_all_day, location_name, location_address, maps_url, cover_media_id, registration_url, status, seo_title, seo_description, created_by, updated_by, created_at, updated_at
`

type UpdateEventParams struct {
	Title           string     `json:"title"`
	Slug            string     `json:"slug"`
	Summary         *string    `json:"summary"`
	DescriptionJson []byte     `json:"description_json"`
	DescriptionHtml *string    `json:"description_html"`
	StartsAt        time.Time  `json:"starts_at"`
	EndsAt          *time.Time `json:"ends_at"`
	IsAllDay        bool       `json:"is_all_day"`
	LocationName    string     `json:"location_name"`
	LocationAddress *string    `json:"location_address"`
	MapsUrl         *string    `json:"maps_url"`
	CoverMediaID    *int64     `json:"cover_media_id"`
	RegistrationUrl *string    `json:"registration_url"`
	Status          string     `json:"status"`
	SeoTitle        *string    `json:"seo_title"`
	SeoDescription  *string    `json:"seo_description"`
	UpdatedBy       *int64     `json:"updated_by"`
	ID              int64      `json:"id"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.Title,
		arg.Slug,
		arg.Summary,
		arg.DescriptionJson,
		arg.DescriptionHtml,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsAllDay,
		arg.LocationName,
		arg.LocationAddress,
		arg.MapsUrl,
		arg.CoverMediaID,
		arg.RegistrationUrl,
		arg.Status,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Summary,
		&i.DescriptionJson,
		&i.DescriptionHtml,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsAllDay,
		&i.LocationName,
		&i.LocationAddress,
		&i.MapsUrl,
		&i.CoverMediaID,
		&i.RegistrationUrl,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
