// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: homepage.sql

package dbgen

import (
	"context"
)

const createHomepageSection = `-- name: CreateHomepageSection :one
INSERT INTO homepage_sections (type, label, position, is_active, config, page_key, updated_by)
VALUES ($1, $2, $3, $4, $5,
        $6, $7)
RETURNING id, type, label, position, is_active, config, page_key, updated_by, created_at, updated_at
`

type CreateHomepageSectionParams struct {
	Type      string `json:"type"`
	Label     string `json:"label"`
	Position  int32  `json:"position"`
	IsActive  bool   `json:"is_active"`
	Config    []byte `json:"config"`
	PageKey   string `json:"page_key"`
	UpdatedBy *int64 `json:"updated_by"`
}

func (q *Queries) CreateHomepageSection(ctx context.Context, arg CreateHomepageSectionParams) (HomepageSection, error) {
	row := q.db.QueryRow(ctx, createHomepageSection,
		arg.Type,
		arg.Label,
		arg.Position,
		arg.IsActive,
		arg.Config,
		arg.PageKey,
		arg.UpdatedBy,
	)
	var i HomepageSection
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Label,
		&i.Position,
		&i.IsActive,
		&i.Config,
		&i.PageKey,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHomepageSection = `-- name: DeleteHomepageSection :execrows
DELETE FROM homepage_sections WHERE id = $1
`

func (q *Queries) DeleteHomepageSection(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteHomepageSection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getHomepageSection = `-- name: GetHomepageSection :one
SELECT id, type, label, position, is_active, config, page_key, updated_by, created_at, updated_at FROM homepage_sections WHERE id = $1
`

func (q *Queries) GetHomepageSection(ctx context.Context, id int64) (HomepageSection, error) {
	row := q.db.QueryRow(ctx, getHomepageSection, id)
	var i HomepageSection
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Label,
		&i.Position,
		&i.IsActive,
		&i.Config,
		&i.PageKey,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveHomepageSections = `-- name: ListActiveHomepageSections :many
SELECT id, type, label, position, is_active, config, page_key, updated_by, created_at, updated_at
FROM homepage_sections
WHERE page_key = $1 AND is_active
ORDER BY position
`

func (q *Queries) ListActiveHomepageSections(ctx context.Context, pageKey string) ([]HomepageSection, error) {
	rows, err := q.db.Query(ctx, listActiveHomepageSections, pageKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomepageSection{}
	for rows.Next() {
		var i HomepageSection
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Label,
			&i.Position,
			&i.IsActive,
			&i.Config,
			&i.PageKey,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomepageSectionIDs = `-- name: ListHomepageSectionIDs :many
SELECT id FROM homepage_sections WHERE page_key = $1 ORDER BY position
`

func (q *Queries) ListHomepageSectionIDs(ctx context.Context, pageKey string) ([]int64, error) {
	rows, err := q.db.Query(ctx, listHomepageSectionIDs, pageKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomepageSections = `-- name: ListHomepageSections :many
SELECT id, type, label, position, is_active, config, page_key, updated_by, created_at, updated_at
FROM homepage_sections
WHERE page_key = $1
ORDER BY position
`

func (q *Queries) ListHomepageSections(ctx context.Context, pageKey string) ([]HomepageSection, error) {
	rows, err := q.db.Query(ctx, listHomepageSections, pageKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HomepageSection{}
	for rows.Next() {
		var i HomepageSection
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Label,
			&i.Position,
			&i.IsActive,
			&i.Config,
			&i.PageKey,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxHomepagePosition = `-- name: MaxHomepagePosition :one
SELECT COALESCE(max(position), 0)::int AS max_position FROM homepage_sections WHERE page_key = $1
`

func (q *Queries) MaxHomepagePosition(ctx context.Context, pageKey string) (int32, error) {
	row := q.db.QueryRow(ctx, maxHomepagePosition, pageKey)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const updateHomepageSection = `-- name: UpdateHomepageSection :one
UPDATE homepage_sections
SET label = $1,
    is_active = $2,
    config = $3,
    updated_by = $4
WHERE id = $5
RETURNING id, type, label, position, is_active, config, page_key, updated_by, created_at, updated_at
`

type UpdateHomepageSectionParams struct {
	Label     string `json:"label"`
	IsActive  bool   `json:"is_active"`
	Config    []byte `json:"config"`
	UpdatedBy *int64 `json:"updated_by"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateHomepageSection(ctx context.Context, arg UpdateHomepageSectionParams) (HomepageSection, error) {
	row := q.db.QueryRow(ctx, updateHomepageSection,
		arg.Label,
		arg.IsActive,
		arg.Config,
		arg.UpdatedBy,
		arg.ID,
	)
	var i HomepageSection
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Label,
		&i.Position,
		&i.IsActive,
		&i.Config,
		&i.PageKey,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateHomepageSectionPosition = `-- name: UpdateHomepageSectionPosition :exec
UPDATE homepage_sections SET position = $1 WHERE id = $2
`

type UpdateHomepageSectionPositionParams struct {
	Position int32 `json:"position"`
	ID       int64 `json:"id"`
}

// UpdateHomepageSectionPosition: reorder uses a two-pass renumber in one tx
// (negative positions first) so the (page_key, position) unique key never clashes.
func (q *Queries) UpdateHomepageSectionPosition(ctx context.Context, arg UpdateHomepageSectionPositionParams) error {
	_, err := q.db.Exec(ctx, updateHomepageSectionPosition, arg.Position, arg.ID)
	return err
}
