// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package dbgen

import (
	"context"
)

const countMedia = `-- name: CountMedia :one
SELECT count(*) FROM media
WHERE ($1::text IS NULL
       OR original_name ILIKE '%' || $1::text || '%'
       OR alt_text ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR mime_type LIKE $2::text || '%')
`

type CountMediaParams struct {
	Q          *string `json:"q"`
	MimePrefix *string `json:"mime_prefix"`
}

func (q *Queries) CountMedia(ctx context.Context, arg CountMediaParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMedia, arg.Q, arg.MimePrefix)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMediaReferences = `-- name: CountMediaReferences :one
SELECT (
    (SELECT count(*) FROM articles WHERE cover_media_id = $1::bigint OR og_media_id = $1::bigint)
  + (SELECT count(*) FROM events WHERE cover_media_id = $1::bigint)
  + (SELECT count(*) FROM alumni_profiles WHERE photo_media_id = $1::bigint)
  + (SELECT count(*) FROM videos WHERE thumbnail_media_id = $1::bigint)
  + (SELECT count(*) FROM pages WHERE og_media_id = $1::bigint)
  + (SELECT count(*) FROM users WHERE avatar_media_id = $1::bigint)
  + (SELECT count(*) FROM site_settings s
     WHERE jsonb_typeof(s.value) = 'object'
       AND (s.value -> 'logo_media_id' = to_jsonb($1::bigint)
            OR s.value -> 'favicon_media_id' = to_jsonb($1::bigint)
            OR s.value -> 'default_og_media_id' = to_jsonb($1::bigint)))
)::bigint AS refs
`

// CountMediaReferences counts every row that points at a media id, including
// soft-deleted articles and media ids stored inside site_settings JSON.
func (q *Queries) CountMediaReferences(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaReferences, id)
	var refs int64
	err := row.Scan(&refs)
	return refs, err
}

const createMedia = `-- name: CreateMedia :one
INSERT INTO media (storage_key, url, original_name, mime_type, size_bytes,
                   width, height, alt_text, caption, uploaded_by)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8,
        $9, $10)
RETURNING id, storage_key, url, original_name, mime_type, size_bytes, width, height, alt_text, caption, uploaded_by, created_at
`

type CreateMediaParams struct {
	StorageKey   string  `json:"storage_key"`
	Url          string  `json:"url"`
	OriginalName string  `json:"original_name"`
	MimeType     string  `json:"mime_type"`
	SizeBytes    int64   `json:"size_bytes"`
	Width        *int32  `json:"width"`
	Height       *int32  `json:"height"`
	AltText      *string `json:"alt_text"`
	Caption      *string `json:"caption"`
	UploadedBy   *int64  `json:"uploaded_by"`
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, createMedia,
		arg.StorageKey,
		arg.Url,
		arg.OriginalName,
		arg.MimeType,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.AltText,
		arg.Caption,
		arg.UploadedBy,
	)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Url,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.AltText,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMedia = `-- name: DeleteMedia :execrows
DELETE FROM media WHERE id = $1
`

func (q *Queries) DeleteMedia(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMedia, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMedia = `-- name: GetMedia :one
SELECT id, storage_key, url, original_name, mime_type, size_bytes, width, height, alt_text, caption, uploaded_by, created_at FROM media WHERE id = $1
`

func (q *Queries) GetMedia(ctx context.Context, id int64) (Medium, error) {
	row := q.db.QueryRow(ctx, getMedia, id)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Url,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.AltText,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listMedia = `-- name: ListMedia :many
SELECT id, storage_key, url, original_name, mime_type, size_bytes, width, height, alt_text, caption, uploaded_by, created_at FROM media
WHERE ($1::text IS NULL
       OR original_name ILIKE '%' || $1::text || '%'
       OR alt_text ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR mime_type LIKE $2::text || '%')
ORDER BY created_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListMediaParams struct {
	Q          *string `json:"q"`
	MimePrefix *string `json:"mime_prefix"`
	Offset     int32   `json:"offset"`
	Limit      int32   `json:"limit"`
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMedia,
		arg.Q,
		arg.MimePrefix,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.Url,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.AltText,
			&i.Caption,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByIDs = `-- name: ListMediaByIDs :many
SELECT id, storage_key, url, original_name, mime_type, size_bytes, width, height, alt_text, caption, uploaded_by, created_at FROM media WHERE id = ANY($1::bigint[]) ORDER BY id
`

func (q *Queries) ListMediaByIDs(ctx context.Context, ids []int64) ([]Medium, error) {
	rows, err := q.db.Query(ctx, listMediaByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Medium{}
	for rows.Next() {
		var i Medium
		if err := rows.Scan(
			&i.ID,
			&i.StorageKey,
			&i.Url,
			&i.OriginalName,
			&i.MimeType,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.AltText,
			&i.Caption,
			&i.UploadedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMediaMeta = `-- name: UpdateMediaMeta :one
UPDATE media SET alt_text = $1, caption = $2
WHERE id = $3
RETURNING id, storage_key, url, original_name, mime_type, size_bytes, width, height, alt_text, caption, uploaded_by, created_at
`

type UpdateMediaMetaParams struct {
	AltText *string `json:"alt_text"`
	Caption *string `json:"caption"`
	ID      int64   `json:"id"`
}

func (q *Queries) UpdateMediaMeta(ctx context.Context, arg UpdateMediaMetaParams) (Medium, error) {
	row := q.db.QueryRow(ctx, updateMediaMeta, arg.AltText, arg.Caption, arg.ID)
	var i Medium
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Url,
		&i.OriginalName,
		&i.MimeType,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.AltText,
		&i.Caption,
		&i.UploadedBy,
		&i.CreatedAt,
	)
	return i, err
}
