// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menus.sql

package dbgen

import (
	"context"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (menu_id, parent_id, label, link_type, link_target, open_new_tab, sort_order, is_active)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8)
RETURNING id
`

type CreateMenuItemParams struct {
	MenuID     int64  `json:"menu_id"`
	ParentID   *int64 `json:"parent_id"`
	Label      string `json:"label"`
	LinkType   string `json:"link_type"`
	LinkTarget string `json:"link_target"`
	OpenNewTab bool   `json:"open_new_tab"`
	SortOrder  int32  `json:"sort_order"`
	IsActive   bool   `json:"is_active"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (int64, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.MenuID,
		arg.ParentID,
		arg.Label,
		arg.LinkType,
		arg.LinkTarget,
		arg.OpenNewTab,
		arg.SortOrder,
		arg.IsActive,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteMenuItems = `-- name: DeleteMenuItems :exec
DELETE FROM menu_items WHERE menu_id = $1
`

func (q *Queries) DeleteMenuItems(ctx context.Context, menuID int64) error {
	_, err := q.db.Exec(ctx, deleteMenuItems, menuID)
	return err
}

const getMenuByCode = `-- name: GetMenuByCode :one
SELECT id, code, name FROM menus WHERE code = $1
`

func (q *Queries) GetMenuByCode(ctx context.Context, code string) (Menu, error) {
	row := q.db.QueryRow(ctx, getMenuByCode, code)
	var i Menu
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const listAllMenuItems = `-- name: ListAllMenuItems :many
SELECT id, menu_id, parent_id, label, link_type, link_target, open_new_tab, sort_order, is_active FROM menu_items
ORDER BY menu_id, parent_id NULLS FIRST, sort_order, id
`

func (q *Queries) ListAllMenuItems(ctx context.Context) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listAllMenuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.ParentID,
			&i.Label,
			&i.LinkType,
			&i.LinkTarget,
			&i.OpenNewTab,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItems = `-- name: ListMenuItems :many
SELECT id, menu_id, parent_id, label, link_type, link_target, open_new_tab, sort_order, is_active FROM menu_items
WHERE menu_id = $1
ORDER BY parent_id NULLS FIRST, sort_order, id
`

func (q *Queries) ListMenuItems(ctx context.Context, menuID int64) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItems, menuID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuItem{}
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.MenuID,
			&i.ParentID,
			&i.Label,
			&i.LinkType,
			&i.LinkTarget,
			&i.OpenNewTab,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenus = `-- name: ListMenus :many
SELECT id, code, name FROM menus ORDER BY id
`

func (q *Queries) ListMenus(ctx context.Context) ([]Menu, error) {
	rows, err := q.db.Query(ctx, listMenus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Menu{}
	for rows.Next() {
		var i Menu
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
