// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AlumniProfile struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	RoleTitle      string    `json:"role_title"`
	ClassYear      *int16    `json:"class_year"`
	ShortBio       string    `json:"short_bio"`
	StoryJson      []byte    `json:"story_json"`
	StoryHtml      *string   `json:"story_html"`
	PhotoMediaID   *int64    `json:"photo_media_id"`
	IsFeatured     bool      `json:"is_featured"`
	SortOrder      int32     `json:"sort_order"`
	Status         string    `json:"status"`
	SeoTitle       *string   `json:"seo_title"`
	SeoDescription *string   `json:"seo_description"`
	CreatedBy      *int64    `json:"created_by"`
	UpdatedBy      *int64    `json:"updated_by"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Article struct {
	ID             int64           `json:"id"`
	Title          string          `json:"title"`
	Slug           string          `json:"slug"`
	Excerpt        *string         `json:"excerpt"`
	ContentJson    []byte          `json:"content_json"`
	ContentHtml    string          `json:"content_html"`
	ContentText    string          `json:"content_text"`
	CoverMediaID   *int64          `json:"cover_media_id"`
	CoverCaption   *string         `json:"cover_caption"`
	CategoryID     int64           `json:"category_id"`
	AuthorID       int64           `json:"author_id"`
	Status         string          `json:"status"`
	PublishedAt    *time.Time      `json:"published_at"`
	IsFeatured     bool            `json:"is_featured"`
	IsBreaking     bool            `json:"is_breaking"`
	ReadingMinutes int16           `json:"reading_minutes"`
	EventDate      *time.Time      `json:"event_date"`
	EventLocation  *string         `json:"event_location"`
	ViewCount      int64           `json:"view_count"`
	SeoTitle       *string         `json:"seo_title"`
	SeoDescription *string         `json:"seo_description"`
	OgMediaID      *int64          `json:"og_media_id"`
	CanonicalUrl   *string         `json:"canonical_url"`
	SearchVector   pgtype.TSVector `json:"search_vector"`
	CreatedBy      *int64          `json:"created_by"`
	UpdatedBy      *int64          `json:"updated_by"`
	CreatedAt      time.Time       `json:"created_at"`
	UpdatedAt      time.Time       `json:"updated_at"`
	DeletedAt      *time.Time      `json:"deleted_at"`
}

type ArticleSlugRedirect struct {
	OldSlug   string    `json:"old_slug"`
	ArticleID int64     `json:"article_id"`
	CreatedAt time.Time `json:"created_at"`
}

type ArticleTag struct {
	ArticleID int64 `json:"article_id"`
	TagID     int64 `json:"tag_id"`
}

type ArticleViewDedup struct {
	ArticleID   int64     `json:"article_id"`
	VisitorHash []byte    `json:"visitor_hash"`
	Day         time.Time `json:"day"`
}

type ArticleViewsDaily struct {
	ArticleID int64     `json:"article_id"`
	Day       time.Time `json:"day"`
	Views     int32     `json:"views"`
}

type AuditLog struct {
	ID         int64       `json:"id"`
	UserID     *int64      `json:"user_id"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   *int64      `json:"entity_id"`
	Summary    string      `json:"summary"`
	Changes    []byte      `json:"changes"`
	Ip         *netip.Addr `json:"ip"`
	CreatedAt  time.Time   `json:"created_at"`
}

type Category struct {
	ID             int64     `json:"id"`
	ParentID       *int64    `json:"parent_id"`
	Name           string    `json:"name"`
	Slug           string    `json:"slug"`
	Description    *string   `json:"description"`
	SortOrder      int32     `json:"sort_order"`
	IsActive       bool      `json:"is_active"`
	SeoTitle       *string   `json:"seo_title"`
	SeoDescription *string   `json:"seo_description"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Event struct {
	ID              int64      `json:"id"`
	Title           string     `json:"title"`
	Slug            string     `json:"slug"`
	Summary         *string    `json:"summary"`
	DescriptionJson []byte     `json:"description_json"`
	DescriptionHtml *string    `json:"description_html"`
	StartsAt        time.Time  `json:"starts_at"`
	EndsAt          *time.Time `json:"ends_at"`
	IsAllDay        bool       `json:"is_all_day"`
	LocationName    string     `json:"location_name"`
	LocationAddress *string    `json:"location_address"`
	MapsUrl         *string    `json:"maps_url"`
	CoverMediaID    *int64     `json:"cover_media_id"`
	RegistrationUrl *string    `json:"registration_url"`
	Status          string     `json:"status"`
	SeoTitle        *string    `json:"seo_title"`
	SeoDescription  *string    `json:"seo_description"`
	CreatedBy       *int64     `json:"created_by"`
	UpdatedBy       *int64     `json:"updated_by"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type HomepageSection struct {
	ID        int64     `json:"id"`
	Type      string    `json:"type"`
	Label     string    `json:"label"`
	Position  int32     `json:"position"`
	IsActive  bool      `json:"is_active"`
	Config    []byte    `json:"config"`
	PageKey   string    `json:"page_key"`
	UpdatedBy *int64    `json:"updated_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Medium struct {
	ID           int64     `json:"id"`
	StorageKey   string    `json:"storage_key"`
	Url          string    `json:"url"`
	OriginalName string    `json:"original_name"`
	MimeType     string    `json:"mime_type"`
	SizeBytes    int64     `json:"size_bytes"`
	Width        *int32    `json:"width"`
	Height       *int32    `json:"height"`
	AltText      *string   `json:"alt_text"`
	Caption      *string   `json:"caption"`
	UploadedBy   *int64    `json:"uploaded_by"`
	CreatedAt    time.Time `json:"created_at"`
}

type Menu struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type MenuItem struct {
	ID         int64  `json:"id"`
	MenuID     int64  `json:"menu_id"`
	ParentID   *int64 `json:"parent_id"`
	Label      string `json:"label"`
	LinkType   string `json:"link_type"`
	LinkTarget string `json:"link_target"`
	OpenNewTab bool   `json:"open_new_tab"`
	SortOrder  int32  `json:"sort_order"`
	IsActive   bool   `json:"is_active"`
}

type Page struct {
	ID             int64     `json:"id"`
	Title          string    `json:"title"`
	Slug           string    `json:"slug"`
	ContentJson    []byte    `json:"content_json"`
	ContentHtml    string    `json:"content_html"`
	Status         string    `json:"status"`
	SeoTitle       *string   `json:"seo_title"`
	SeoDescription *string   `json:"seo_description"`
	OgMediaID      *int64    `json:"og_media_id"`
	CreatedBy      *int64    `json:"created_by"`
	UpdatedBy      *int64    `json:"updated_by"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Permission struct {
	ID          int64  `json:"id"`
	Code        string `json:"code"`
	Description string `json:"description"`
}

type RefreshToken struct {
	ID        int64       `json:"id"`
	UserID    int64       `json:"user_id"`
	FamilyID  pgtype.UUID `json:"family_id"`
	TokenHash []byte      `json:"token_hash"`
	ExpiresAt time.Time   `json:"expires_at"`
	RotatedAt *time.Time  `json:"rotated_at"`
	RevokedAt *time.Time  `json:"revoked_at"`
	UserAgent *string     `json:"user_agent"`
	Ip        *netip.Addr `json:"ip"`
	CreatedAt time.Time   `json:"created_at"`
}

type Role struct {
	ID          int64     `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
}

type RolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type SiteSetting struct {
	Key       string    `json:"key"`
	Value     []byte    `json:"value"`
	UpdatedBy *int64    `json:"updated_by"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Snippet struct {
	ID        int64      `json:"id"`
	Type      string     `json:"type"`
	Title     *string    `json:"title"`
	Body      string     `json:"body"`
	Source    *string    `json:"source"`
	LinkUrl   *string    `json:"link_url"`
	SortOrder int32      `json:"sort_order"`
	IsActive  bool       `json:"is_active"`
	StartsAt  *time.Time `json:"starts_at"`
	EndsAt    *time.Time `json:"ends_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID            int64      `json:"id"`
	Email         *string    `json:"email"`
	PasswordHash  *string    `json:"password_hash"`
	DisplayName   string     `json:"display_name"`
	Slug          string     `json:"slug"`
	Title         *string    `json:"title"`
	Bio           *string    `json:"bio"`
	AvatarMediaID *int64     `json:"avatar_media_id"`
	CanLogin      bool       `json:"can_login"`
	IsActive      bool       `json:"is_active"`
	LastLoginAt   *time.Time `json:"last_login_at"`
	PermVersion   int32      `json:"perm_version"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
	// User must change the password before using the admin dashboard.
	MustChangePassword bool `json:"must_change_password"`
	// Normalized Indonesian mobile number without +62/0 prefix (^8[0-9]{8,11}$).
	Phone *string `json:"phone"`
}

type UserRole struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}

type Video struct {
	ID               int64     `json:"id"`
	Title            string    `json:"title"`
	Slug             string    `json:"slug"`
	YoutubeID        string    `json:"youtube_id"`
	Description      *string   `json:"description"`
	DurationSeconds  *int32    `json:"duration_seconds"`
	ViewCount        *int64    `json:"view_count"`
	ThumbnailMediaID *int64    `json:"thumbnail_media_id"`
	PublishedAt      time.Time `json:"published_at"`
	IsFeatured       bool      `json:"is_featured"`
	Status           string    `json:"status"`
	CreatedBy        *int64    `json:"created_by"`
	UpdatedBy        *int64    `json:"updated_by"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}
