// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package dbgen

import (
	"context"
	"time"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages (title, slug, content_json, content_html, status, seo_title, seo_description,
                   og_media_id, created_by, updated_by)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8,
        $9, $10)
RETURNING id, title, slug, content_json, content_html, status, seo_title, seo_description, og_media_id, created_by, updated_by, created_at, updated_at
`

type CreatePageParams struct {
	Title          string  `json:"title"`
	Slug           string  `json:"slug"`
	ContentJson    []byte  `json:"content_json"`
	ContentHtml    string  `json:"content_html"`
	Status         string  `json:"status"`
	SeoTitle       *string `json:"seo_title"`
	SeoDescription *string `json:"seo_description"`
	OgMediaID      *int64  `json:"og_media_id"`
	CreatedBy      *int64  `json:"created_by"`
	UpdatedBy      *int64  `json:"updated_by"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.Title,
		arg.Slug,
		arg.ContentJson,
		arg.ContentHtml,
		arg.Status,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.OgMediaID,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.ContentHtml,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgMediaID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :execrows
DELETE FROM pages WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePage, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPage = `-- name: GetPage :one
SELECT id, title, slug, content_json, content_html, status, seo_title, seo_description, og_media_id, created_by, updated_by, created_at, updated_at FROM pages WHERE id = $1
`

func (q *Queries) GetPage(ctx context.Context, id int64) (Page, error) {
	row := q.db.QueryRow(ctx, getPage, id)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.ContentHtml,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgMediaID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, title, slug, content_json, content_html, status, seo_title, seo_description, og_media_id, created_by, updated_by, created_at, updated_at FROM pages WHERE slug = $1
`

func (q *Queries) GetPageBySlug(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRow(ctx, getPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.ContentHtml,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgMediaID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPublishedPageBySlug = `-- name: GetPublishedPageBySlug :one
SELECT id, title, slug, content_json, content_html, status, seo_title, seo_description, og_media_id, created_by, updated_by, created_at, updated_at FROM pages WHERE slug = $1 AND status = 'published'
`

func (q *Queries) GetPublishedPageBySlug(ctx context.Context, slug string) (Page, error) {
	row := q.db.QueryRow(ctx, getPublishedPageBySlug, slug)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.ContentHtml,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgMediaID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT id, title, slug, content_json, content_html, status, seo_title, seo_description, og_media_id, created_by, updated_by, created_at, updated_at FROM pages ORDER BY title, id
`

func (q *Queries) ListPages(ctx context.Context) ([]Page, error) {
	rows, err := q.db.Query(ctx, listPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Page{}
	for rows.Next() {
		var i Page
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.ContentJson,
			&i.ContentHtml,
			&i.Status,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.OgMediaID,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedPages = `-- name: ListPublishedPages :many
SELECT slug, title, updated_at FROM pages
WHERE status = 'published'
ORDER BY title, id
`

type ListPublishedPagesRow struct {
	Slug      string    `json:"slug"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListPublishedPages(ctx context.Context) ([]ListPublishedPagesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedPagesRow{}
	for rows.Next() {
		var i ListPublishedPagesRow
		if err := rows.Scan(&i.Slug, &i.Title, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pageSlugExists = `-- name: PageSlugExists :one
SELECT EXISTS (
  SELECT 1 FROM pages WHERE slug = $1::text AND id <> $2::bigint
) AS exists
`

type PageSlugExistsParams struct {
	Slug      string `json:"slug"`
	ExcludeID int64  `json:"exclude_id"`
}

func (q *Queries) PageSlugExists(ctx context.Context, arg PageSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, pageSlugExists, arg.Slug, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET title = $1,
    slug = $2,
    content_json = $3,
    content_html = $4,
    status = $5,
    seo_title = $6,
    seo_description = $7,
    og_media_id = $8,
    updated_by = $9
WHERE id = $10
RETURNING id, title, slug, content_json, content_html, status, seo_title, seo_description, og_media_id, created_by, updated_by, created_at, updated_at
`

type UpdatePageParams struct {
	Title          string  `json:"title"`
	Slug           string  `json:"slug"`
	ContentJson    []byte  `json:"content_json"`
	ContentHtml    string  `json:"content_html"`
	Status         string  `json:"status"`
	SeoTitle       *string `json:"seo_title"`
	SeoDescription *string `json:"seo_description"`
	OgMediaID      *int64  `json:"og_media_id"`
	UpdatedBy      *int64  `json:"updated_by"`
	ID             int64   `json:"id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Page, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.Title,
		arg.Slug,
		arg.ContentJson,
		arg.ContentHtml,
		arg.Status,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.OgMediaID,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Page
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.ContentJson,
		&i.ContentHtml,
		&i.Status,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.OgMediaID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
