// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package dbgen

import (
	"context"
	"time"
)

const addRolePermissions = `-- name: AddRolePermissions :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT $1::bigint, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type AddRolePermissionsParams struct {
	RoleID        int64   `json:"role_id"`
	PermissionIds []int64 `json:"permission_ids"`
}

func (q *Queries) AddRolePermissions(ctx context.Context, arg AddRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, addRolePermissions, arg.RoleID, arg.PermissionIds)
	return err
}

const countRoleUsers = `-- name: CountRoleUsers :one
SELECT count(*) FROM user_roles WHERE role_id = $1
`

func (q *Queries) CountRoleUsers(ctx context.Context, roleID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRoleUsers, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (code, name, description)
VALUES ($1, $2, $3)
RETURNING id, code, name, description, is_system, created_at
`

type CreateRoleParams struct {
	Code        string  `json:"code"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Code, arg.Name, arg.Description)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :execrows
DELETE FROM roles WHERE id = $1 AND NOT is_system
`

func (q *Queries) DeleteRole(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRole, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID int64) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, code, name, description, is_system, created_at
FROM roles
WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const listAllRolePermissions = `-- name: ListAllRolePermissions :many
SELECT rp.role_id, p.code
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
ORDER BY rp.role_id, p.code
`

type ListAllRolePermissionsRow struct {
	RoleID int64  `json:"role_id"`
	Code   string `json:"code"`
}

func (q *Queries) ListAllRolePermissions(ctx context.Context) ([]ListAllRolePermissionsRow, error) {
	rows, err := q.db.Query(ctx, listAllRolePermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRolePermissionsRow{}
	for rows.Next() {
		var i ListAllRolePermissionsRow
		if err := rows.Scan(&i.RoleID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, code, description FROM permissions ORDER BY code
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Code, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByCodes = `-- name: ListPermissionsByCodes :many
SELECT id, code, description FROM permissions
WHERE code = ANY($1::text[])
ORDER BY code
`

func (q *Queries) ListPermissionsByCodes(ctx context.Context, codes []string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByCodes, codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Code, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionCodes = `-- name: ListRolePermissionCodes :many
SELECT p.code
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.code
`

func (q *Queries) ListRolePermissionCodes(ctx context.Context, roleID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolePermissionCodes, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT r.id, r.code, r.name, r.description, r.is_system, r.created_at,
       (SELECT count(*) FROM user_roles ur WHERE ur.role_id = r.id) AS user_count
FROM roles r
ORDER BY r.is_system DESC, r.code
`

type ListRolesRow struct {
	ID          int64     `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	IsSystem    bool      `json:"is_system"`
	CreatedAt   time.Time `json:"created_at"`
	UserCount   int64     `json:"user_count"`
}

func (q *Queries) ListRoles(ctx context.Context) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UserCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByIDs = `-- name: ListRolesByIDs :many
SELECT id, code, name, description, is_system, created_at
FROM roles
WHERE id = ANY($1::bigint[])
ORDER BY code
`

func (q *Queries) ListRolesByIDs(ctx context.Context, ids []int64) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles SET name = $1, description = $2
WHERE id = $3
RETURNING id, code, name, description, is_system, created_at
`

type UpdateRoleParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole, arg.Name, arg.Description, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}
