// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package dbgen

import (
	"context"
)

const countSearchArticles = `-- name: CountSearchArticles :one
SELECT count(*)
FROM articles a
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
  AND a.search_vector @@ websearch_to_tsquery('simple', immutable_unaccent($1::text))
`

func (q *Queries) CountSearchArticles(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchArticles, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchArticlesFuzzy = `-- name: CountSearchArticlesFuzzy :one
SELECT count(*)
FROM articles a
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
  AND word_similarity(immutable_unaccent($1::text), immutable_unaccent(a.title)) > 0.3
`

func (q *Queries) CountSearchArticlesFuzzy(ctx context.Context, query string) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchArticlesFuzzy, query)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const searchArticles = `-- name: SearchArticles :many

SELECT a.id,
       ts_rank_cd(a.search_vector, q.query)::float8 AS rank,
       ts_headline('simple', a.content_text, q.query,
                   'MaxWords=35, MinWords=15, MaxFragments=1, StartSel=<mark>, StopSel=</mark>')::text AS headline
FROM articles a,
     (SELECT websearch_to_tsquery('simple', immutable_unaccent($1::text)) AS query) q
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
  AND a.search_vector @@ q.query
ORDER BY rank DESC, a.published_at DESC, a.id DESC
LIMIT $3 OFFSET $2
`

type SearchArticlesParams struct {
	Query  string `json:"query"`
	Offset int32  `json:"offset"`
	Limit  int32  `json:"limit"`
}

type SearchArticlesRow struct {
	ID       int64   `json:"id"`
	Rank     float64 `json:"rank"`
	Headline string  `json:"headline"`
}

// Full-text search over articles.search_vector ('simple' config, unaccented).
func (q *Queries) SearchArticles(ctx context.Context, arg SearchArticlesParams) ([]SearchArticlesRow, error) {
	rows, err := q.db.Query(ctx, searchArticles, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArticlesRow{}
	for rows.Next() {
		var i SearchArticlesRow
		if err := rows.Scan(&i.ID, &i.Rank, &i.Headline); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArticlesFuzzy = `-- name: SearchArticlesFuzzy :many
SELECT a.id,
       word_similarity(immutable_unaccent($1::text), immutable_unaccent(a.title))::float8 AS sim
FROM articles a
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
  AND word_similarity(immutable_unaccent($1::text), immutable_unaccent(a.title)) > 0.3
ORDER BY sim DESC, a.published_at DESC, a.id DESC
LIMIT $3 OFFSET $2
`

type SearchArticlesFuzzyParams struct {
	Query  string `json:"query"`
	Offset int32  `json:"offset"`
	Limit  int32  `json:"limit"`
}

type SearchArticlesFuzzyRow struct {
	ID  int64   `json:"id"`
	Sim float64 `json:"sim"`
}

// Fuzzy fallback on the title (pg_trgm word_similarity(query, title) > 0.3).
func (q *Queries) SearchArticlesFuzzy(ctx context.Context, arg SearchArticlesFuzzyParams) ([]SearchArticlesFuzzyRow, error) {
	rows, err := q.db.Query(ctx, searchArticlesFuzzy, arg.Query, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchArticlesFuzzyRow{}
	for rows.Next() {
		var i SearchArticlesFuzzyRow
		if err := rows.Scan(&i.ID, &i.Sim); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
