// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbgen

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT key, value, updated_by, updated_at
FROM site_settings
WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (SiteSetting, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var i SiteSetting
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT key, value, updated_by, updated_at
FROM site_settings
ORDER BY key
`

func (q *Queries) ListSettings(ctx context.Context) ([]SiteSetting, error) {
	rows, err := q.db.Query(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SiteSetting{}
	for rows.Next() {
		var i SiteSetting
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO site_settings (key, value, updated_by)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET value = EXCLUDED.value,
    updated_by = EXCLUDED.updated_by
`

type UpsertSettingParams struct {
	Key       string `json:"key"`
	Value     []byte `json:"value"`
	UpdatedBy *int64 `json:"updated_by"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.Exec(ctx, upsertSetting, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}
