// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snippets.sql

package dbgen

import (
	"context"
	"time"
)

const countSnippetTransitions = `-- name: CountSnippetTransitions :one
SELECT count(*) FROM snippets
WHERE is_active
  AND ((starts_at > $1::timestamptz AND starts_at <= $2::timestamptz)
       OR (ends_at > $1::timestamptz AND ends_at <= $2::timestamptz))
`

type CountSnippetTransitionsParams struct {
	Since time.Time `json:"since"`
	Now   time.Time `json:"now"`
}

// CountSnippetTransitions: active snippets whose window opened or closed in (since, now].
func (q *Queries) CountSnippetTransitions(ctx context.Context, arg CountSnippetTransitionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSnippetTransitions, arg.Since, arg.Now)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSnippet = `-- name: CreateSnippet :one

INSERT INTO snippets (type, title, body, source, link_url, sort_order, is_active, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9)
RETURNING id, type, title, body, source, link_url, sort_order, is_active, starts_at, ends_at, created_at, updated_at
`

type CreateSnippetParams struct {
	Type      string     `json:"type"`
	Title     *string    `json:"title"`
	Body      string     `json:"body"`
	Source    *string    `json:"source"`
	LinkUrl   *string    `json:"link_url"`
	SortOrder int32      `json:"sort_order"`
	IsActive  bool       `json:"is_active"`
	StartsAt  *time.Time `json:"starts_at"`
	EndsAt    *time.Time `json:"ends_at"`
}

// Active window predicate (ListActive*):
//
//	is_active AND (starts_at IS NULL OR starts_at <= now) AND (ends_at IS NULL OR ends_at > now)
func (q *Queries) CreateSnippet(ctx context.Context, arg CreateSnippetParams) (Snippet, error) {
	row := q.db.QueryRow(ctx, createSnippet,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.LinkUrl,
		arg.SortOrder,
		arg.IsActive,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.LinkUrl,
		&i.SortOrder,
		&i.IsActive,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSnippet = `-- name: DeleteSnippet :execrows
DELETE FROM snippets WHERE id = $1
`

func (q *Queries) DeleteSnippet(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSnippet, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSnippet = `-- name: GetSnippet :one
SELECT id, type, title, body, source, link_url, sort_order, is_active, starts_at, ends_at, created_at, updated_at FROM snippets WHERE id = $1
`

func (q *Queries) GetSnippet(ctx context.Context, id int64) (Snippet, error) {
	row := q.db.QueryRow(ctx, getSnippet, id)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.LinkUrl,
		&i.SortOrder,
		&i.IsActive,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSnippets = `-- name: ListActiveSnippets :many
SELECT id, type, title, body, source, link_url, sort_order, is_active, starts_at, ends_at, created_at, updated_at FROM snippets
WHERE ($1::text IS NULL OR type = $1::text)
  AND is_active
  AND (starts_at IS NULL OR starts_at <= $2::timestamptz)
  AND (ends_at IS NULL OR ends_at > $2::timestamptz)
ORDER BY sort_order, id
`

type ListActiveSnippetsParams struct {
	Type *string   `json:"type"`
	Now  time.Time `json:"now"`
}

func (q *Queries) ListActiveSnippets(ctx context.Context, arg ListActiveSnippetsParams) ([]Snippet, error) {
	rows, err := q.db.Query(ctx, listActiveSnippets, arg.Type, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snippet{}
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.LinkUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnippetsAdmin = `-- name: ListSnippetsAdmin :many
SELECT id, type, title, body, source, link_url, sort_order, is_active, starts_at, ends_at, created_at, updated_at FROM snippets
WHERE $1::text IS NULL OR type = $1::text
ORDER BY type, sort_order, id
`

func (q *Queries) ListSnippetsAdmin(ctx context.Context, type_ *string) ([]Snippet, error) {
	rows, err := q.db.Query(ctx, listSnippetsAdmin, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snippet{}
	for rows.Next() {
		var i Snippet
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.LinkUrl,
			&i.SortOrder,
			&i.IsActive,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSnippet = `-- name: UpdateSnippet :one
UPDATE snippets
SET type = $1,
    title = $2,
    body = $3,
    source = $4,
    link_url = $5,
    sort_order = $6,
    is_active = $7,
    starts_at = $8,
    ends_at = $9
WHERE id = $10
RETURNING id, type, title, body, source, link_url, sort_order, is_active, starts_at, ends_at, created_at, updated_at
`

type UpdateSnippetParams struct {
	Type      string     `json:"type"`
	Title     *string    `json:"title"`
	Body      string     `json:"body"`
	Source    *string    `json:"source"`
	LinkUrl   *string    `json:"link_url"`
	SortOrder int32      `json:"sort_order"`
	IsActive  bool       `json:"is_active"`
	StartsAt  *time.Time `json:"starts_at"`
	EndsAt    *time.Time `json:"ends_at"`
	ID        int64      `json:"id"`
}

func (q *Queries) UpdateSnippet(ctx context.Context, arg UpdateSnippetParams) (Snippet, error) {
	row := q.db.QueryRow(ctx, updateSnippet,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.LinkUrl,
		arg.SortOrder,
		arg.IsActive,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
	)
	var i Snippet
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.LinkUrl,
		&i.SortOrder,
		&i.IsActive,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSnippetOrder = `-- name: UpdateSnippetOrder :exec
UPDATE snippets SET sort_order = $1 WHERE id = $2
`

type UpdateSnippetOrderParams struct {
	SortOrder int32 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateSnippetOrder(ctx context.Context, arg UpdateSnippetOrderParams) error {
	_, err := q.db.Exec(ctx, updateSnippetOrder, arg.SortOrder, arg.ID)
	return err
}
