// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package dbgen

import (
	"context"
	"time"
)

const addArticleTags = `-- name: AddArticleTags :exec
INSERT INTO article_tags (article_id, tag_id)
SELECT $1::bigint, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type AddArticleTagsParams struct {
	ArticleID int64   `json:"article_id"`
	TagIds    []int64 `json:"tag_ids"`
}

func (q *Queries) AddArticleTags(ctx context.Context, arg AddArticleTagsParams) error {
	_, err := q.db.Exec(ctx, addArticleTags, arg.ArticleID, arg.TagIds)
	return err
}

const countTags = `-- name: CountTags :one
SELECT count(*) FROM tags t
WHERE $1::text IS NULL OR t.name ILIKE '%' || $1::text || '%'
`

func (q *Queries) CountTags(ctx context.Context, search *string) (int64, error) {
	row := q.db.QueryRow(ctx, countTags, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name, slug) VALUES ($1, $2)
RETURNING id, name, slug, created_at
`

type CreateTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, createTag, arg.Name, arg.Slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const deleteArticleTags = `-- name: DeleteArticleTags :exec
DELETE FROM article_tags WHERE article_id = $1
`

func (q *Queries) DeleteArticleTags(ctx context.Context, articleID int64) error {
	_, err := q.db.Exec(ctx, deleteArticleTags, articleID)
	return err
}

const deleteTag = `-- name: DeleteTag :execrows
DELETE FROM tags WHERE id = $1
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTag, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrCreateTag = `-- name: GetOrCreateTag :one
INSERT INTO tags (name, slug) VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET name = tags.name
RETURNING id, name, slug, created_at
`

type GetOrCreateTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) GetOrCreateTag(ctx context.Context, arg GetOrCreateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, getOrCreateTag, arg.Name, arg.Slug)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getTag = `-- name: GetTag :one
SELECT id, name, slug, created_at FROM tags WHERE id = $1
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRow(ctx, getTag, id)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT t.id, t.name, t.slug, t.created_at,
       (SELECT count(*) FROM article_tags at JOIN articles a ON a.id = at.article_id
        WHERE at.tag_id = t.id
          AND a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL)::bigint AS article_count
FROM tags t
WHERE t.slug = $1
`

type GetTagBySlugRow struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Slug         string    `json:"slug"`
	CreatedAt    time.Time `json:"created_at"`
	ArticleCount int64     `json:"article_count"`
}

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (GetTagBySlugRow, error) {
	row := q.db.QueryRow(ctx, getTagBySlug, slug)
	var i GetTagBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.ArticleCount,
	)
	return i, err
}

const listArticleTags = `-- name: ListArticleTags :many
SELECT t.id, t.name, t.slug, t.created_at FROM tags t
JOIN article_tags at ON at.tag_id = t.id
WHERE at.article_id = $1
ORDER BY t.name
`

func (q *Queries) ListArticleTags(ctx context.Context, articleID int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listArticleTags, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArticleTagsByArticleIDs = `-- name: ListArticleTagsByArticleIDs :many
SELECT at.article_id, t.id, t.name, t.slug
FROM article_tags at
JOIN tags t ON t.id = at.tag_id
WHERE at.article_id = ANY($1::bigint[])
ORDER BY at.article_id, t.name
`

type ListArticleTagsByArticleIDsRow struct {
	ArticleID int64  `json:"article_id"`
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Slug      string `json:"slug"`
}

func (q *Queries) ListArticleTagsByArticleIDs(ctx context.Context, articleIds []int64) ([]ListArticleTagsByArticleIDsRow, error) {
	rows, err := q.db.Query(ctx, listArticleTagsByArticleIDs, articleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListArticleTagsByArticleIDsRow{}
	for rows.Next() {
		var i ListArticleTagsByArticleIDsRow
		if err := rows.Scan(
			&i.ArticleID,
			&i.ID,
			&i.Name,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPopularTags = `-- name: ListPopularTags :many
SELECT t.id, t.name, t.slug, count(a.id)::bigint AS article_count
FROM tags t
JOIN article_tags at ON at.tag_id = t.id
JOIN articles a ON a.id = at.article_id
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
GROUP BY t.id
ORDER BY count(a.id) DESC, t.name
LIMIT $1
`

type ListPopularTagsRow struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	Slug         string `json:"slug"`
	ArticleCount int64  `json:"article_count"`
}

func (q *Queries) ListPopularTags(ctx context.Context, limit int32) ([]ListPopularTagsRow, error) {
	rows, err := q.db.Query(ctx, listPopularTags, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPopularTagsRow{}
	for rows.Next() {
		var i ListPopularTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT t.id, t.name, t.slug, t.created_at,
       (SELECT count(*) FROM article_tags at JOIN articles a ON a.id = at.article_id
        WHERE at.tag_id = t.id
          AND a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL)::bigint AS article_count
FROM tags t
WHERE $1::text IS NULL OR t.name ILIKE '%' || $1::text || '%'
ORDER BY t.name, t.id
LIMIT $3 OFFSET $2
`

type ListTagsParams struct {
	Q      *string `json:"q"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

type ListTagsRow struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Slug         string    `json:"slug"`
	CreatedAt    time.Time `json:"created_at"`
	ArticleCount int64     `json:"article_count"`
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags, arg.Q, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsRow{}
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.ArticleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByIDs = `-- name: ListTagsByIDs :many
SELECT id, name, slug, created_at FROM tags WHERE id = ANY($1::bigint[]) ORDER BY name
`

func (q *Queries) ListTagsByIDs(ctx context.Context, ids []int64) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsWithArticles = `-- name: ListTagsWithArticles :many
SELECT t.slug, t.name, max(a.updated_at)::timestamptz AS updated_at
FROM tags t
JOIN article_tags at ON at.tag_id = t.id
JOIN articles a ON a.id = at.article_id
WHERE a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
GROUP BY t.id
ORDER BY t.slug
`

type ListTagsWithArticlesRow struct {
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

// ListTagsWithArticles: tags with >= 1 published article (sitemap).
func (q *Queries) ListTagsWithArticles(ctx context.Context) ([]ListTagsWithArticlesRow, error) {
	rows, err := q.db.Query(ctx, listTagsWithArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTagsWithArticlesRow{}
	for rows.Next() {
		var i ListTagsWithArticlesRow
		if err := rows.Scan(&i.Slug, &i.Name, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeTagArticles = `-- name: MergeTagArticles :exec
INSERT INTO article_tags (article_id, tag_id)
SELECT at.article_id, $1::bigint
FROM article_tags at
WHERE at.tag_id = $2::bigint
ON CONFLICT DO NOTHING
`

type MergeTagArticlesParams struct {
	IntoID int64 `json:"into_id"`
	FromID int64 `json:"from_id"`
}

func (q *Queries) MergeTagArticles(ctx context.Context, arg MergeTagArticlesParams) error {
	_, err := q.db.Exec(ctx, mergeTagArticles, arg.IntoID, arg.FromID)
	return err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET name = $1, slug = $2
WHERE id = $3
RETURNING id, name, slug, created_at
`

type UpdateTagParams struct {
	Name string `json:"name"`
	Slug string `json:"slug"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, updateTag, arg.Name, arg.Slug, arg.ID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
