// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbgen

import (
	"context"
	"time"
)

const addUserRoles = `-- name: AddUserRoles :exec
INSERT INTO user_roles (user_id, role_id)
SELECT $1::bigint, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type AddUserRolesParams struct {
	UserID  int64   `json:"user_id"`
	RoleIds []int64 `json:"role_ids"`
}

func (q *Queries) AddUserRoles(ctx context.Context, arg AddUserRolesParams) error {
	_, err := q.db.Exec(ctx, addUserRoles, arg.UserID, arg.RoleIds)
	return err
}

const bumpPermVersionByRole = `-- name: BumpPermVersionByRole :exec
UPDATE users SET perm_version = perm_version + 1
WHERE id IN (SELECT user_id FROM user_roles WHERE role_id = $1)
`

func (q *Queries) BumpPermVersionByRole(ctx context.Context, roleID int64) error {
	_, err := q.db.Exec(ctx, bumpPermVersionByRole, roleID)
	return err
}

const bumpUserPermVersion = `-- name: BumpUserPermVersion :one
UPDATE users SET perm_version = perm_version + 1 WHERE id = $1
RETURNING perm_version
`

func (q *Queries) BumpUserPermVersion(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, bumpUserPermVersion, id)
	var perm_version int32
	err := row.Scan(&perm_version)
	return perm_version, err
}

const clearUserCredentials = `-- name: ClearUserCredentials :exec
UPDATE users SET email = NULL, password_hash = NULL, can_login = false WHERE id = $1
`

func (q *Queries) ClearUserCredentials(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, clearUserCredentials, id)
	return err
}

const countActiveSuperAdminsExcept = `-- name: CountActiveSuperAdminsExcept :one
SELECT count(DISTINCT u.id)
FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles r ON r.id = ur.role_id
WHERE r.code = 'super_admin'
  AND u.is_active AND u.can_login
  AND u.id <> $1::bigint
`

func (q *Queries) CountActiveSuperAdminsExcept(ctx context.Context, excludeUserID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSuperAdminsExcept, excludeUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersFiltered = `-- name: CountUsersFiltered :one
SELECT count(*)
FROM users u
WHERE ($1::text IS NULL
       OR u.display_name ILIKE '%' || $1::text || '%'
       OR u.email::text ILIKE '%' || $1::text || '%')
  AND ($2::boolean IS NULL OR u.can_login = $2::boolean)
  AND ($3::boolean IS NULL OR u.is_active = $3::boolean)
  AND ($4::text IS NULL OR EXISTS (
        SELECT 1 FROM user_roles ur JOIN roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id AND r.code = $4::text))
`

type CountUsersFilteredParams struct {
	Q        *string `json:"q"`
	CanLogin *bool   `json:"can_login"`
	IsActive *bool   `json:"is_active"`
	RoleCode *string `json:"role_code"`
}

func (q *Queries) CountUsersFiltered(ctx context.Context, arg CountUsersFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersFiltered,
		arg.Q,
		arg.CanLogin,
		arg.IsActive,
		arg.RoleCode,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name, slug, title, bio, avatar_media_id, can_login, is_active)
VALUES ($1::citext, $2, $3, $4,
        $5, $6, $7, $8, $9)
RETURNING id, email, display_name, slug, title, bio, avatar_media_id,
          can_login, is_active, last_login_at, perm_version, created_at, updated_at
`

type CreateUserParams struct {
	Email         *string `json:"email"`
	PasswordHash  *string `json:"password_hash"`
	DisplayName   string  `json:"display_name"`
	Slug          string  `json:"slug"`
	Title         *string `json:"title"`
	Bio           *string `json:"bio"`
	AvatarMediaID *int64  `json:"avatar_media_id"`
	CanLogin      bool    `json:"can_login"`
	IsActive      bool    `json:"is_active"`
}

type CreateUserRow struct {
	ID            int64      `json:"id"`
	Email         *string    `json:"email"`
	DisplayName   string     `json:"display_name"`
	Slug          string     `json:"slug"`
	Title         *string    `json:"title"`
	Bio           *string    `json:"bio"`
	AvatarMediaID *int64     `json:"avatar_media_id"`
	CanLogin      bool       `json:"can_login"`
	IsActive      bool       `json:"is_active"`
	LastLoginAt   *time.Time `json:"last_login_at"`
	PermVersion   int32      `json:"perm_version"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Slug,
		arg.Title,
		arg.Bio,
		arg.AvatarMediaID,
		arg.CanLogin,
		arg.IsActive,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Slug,
		&i.Title,
		&i.Bio,
		&i.AvatarMediaID,
		&i.CanLogin,
		&i.IsActive,
		&i.LastLoginAt,
		&i.PermVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userID)
	return err
}

const getUserAccess = `-- name: GetUserAccess :one
SELECT is_active, can_login, perm_version FROM users WHERE id = $1
`

type GetUserAccessRow struct {
	IsActive    bool  `json:"is_active"`
	CanLogin    bool  `json:"can_login"`
	PermVersion int32 `json:"perm_version"`
}

func (q *Queries) GetUserAccess(ctx context.Context, id int64) (GetUserAccessRow, error) {
	row := q.db.QueryRow(ctx, getUserAccess, id)
	var i GetUserAccessRow
	err := row.Scan(&i.IsActive, &i.CanLogin, &i.PermVersion)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, slug, title, bio, avatar_media_id,
       can_login, is_active, last_login_at, perm_version, created_at, updated_at
FROM users
WHERE email = $1::citext
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Slug,
		&i.Title,
		&i.Bio,
		&i.AvatarMediaID,
		&i.CanLogin,
		&i.IsActive,
		&i.LastLoginAt,
		&i.PermVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, slug, title, bio, avatar_media_id,
       can_login, is_active, last_login_at, perm_version, created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            int64      `json:"id"`
	Email         *string    `json:"email"`
	DisplayName   string     `json:"display_name"`
	Slug          string     `json:"slug"`
	Title         *string    `json:"title"`
	Bio           *string    `json:"bio"`
	AvatarMediaID *int64     `json:"avatar_media_id"`
	CanLogin      bool       `json:"can_login"`
	IsActive      bool       `json:"is_active"`
	LastLoginAt   *time.Time `json:"last_login_at"`
	PermVersion   int32      `json:"perm_version"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Slug,
		&i.Title,
		&i.Bio,
		&i.AvatarMediaID,
		&i.CanLogin,
		&i.IsActive,
		&i.LastLoginAt,
		&i.PermVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySlug = `-- name: GetUserBySlug :one
SELECT id, email, display_name, slug, title, bio, avatar_media_id,
       can_login, is_active, last_login_at, perm_version, created_at, updated_at
FROM users
WHERE slug = $1
`

type GetUserBySlugRow struct {
	ID            int64      `json:"id"`
	Email         *string    `json:"email"`
	DisplayName   string     `json:"display_name"`
	Slug          string     `json:"slug"`
	Title         *string    `json:"title"`
	Bio           *string    `json:"bio"`
	AvatarMediaID *int64     `json:"avatar_media_id"`
	CanLogin      bool       `json:"can_login"`
	IsActive      bool       `json:"is_active"`
	LastLoginAt   *time.Time `json:"last_login_at"`
	PermVersion   int32      `json:"perm_version"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

func (q *Queries) GetUserBySlug(ctx context.Context, slug string) (GetUserBySlugRow, error) {
	row := q.db.QueryRow(ctx, getUserBySlug, slug)
	var i GetUserBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Slug,
		&i.Title,
		&i.Bio,
		&i.AvatarMediaID,
		&i.CanLogin,
		&i.IsActive,
		&i.LastLoginAt,
		&i.PermVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPasswordHash = `-- name: GetUserPasswordHash :one
SELECT password_hash FROM users WHERE id = $1
`

func (q *Queries) GetUserPasswordHash(ctx context.Context, id int64) (*string, error) {
	row := q.db.QueryRow(ctx, getUserPasswordHash, id)
	var password_hash *string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, display_name, slug, title, bio, avatar_media_id
FROM users
WHERE is_active
ORDER BY display_name, id
`

type ListAuthorsRow struct {
	ID            int64   `json:"id"`
	DisplayName   string  `json:"display_name"`
	Slug          string  `json:"slug"`
	Title         *string `json:"title"`
	Bio           *string `json:"bio"`
	AvatarMediaID *int64  `json:"avatar_media_id"`
}

func (q *Queries) ListAuthors(ctx context.Context) ([]ListAuthorsRow, error) {
	rows, err := q.db.Query(ctx, listAuthors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorsRow{}
	for rows.Next() {
		var i ListAuthorsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Slug,
			&i.Title,
			&i.Bio,
			&i.AvatarMediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthorsWithPublishedArticles = `-- name: ListAuthorsWithPublishedArticles :many
SELECT u.slug, u.display_name, max(a.published_at)::timestamptz AS last_published_at,
       max(a.updated_at)::timestamptz AS updated_at
FROM users u
JOIN articles a ON a.author_id = u.id
WHERE u.is_active
  AND a.status = 'published' AND a.published_at <= now() AND a.deleted_at IS NULL
GROUP BY u.id
ORDER BY u.slug
`

type ListAuthorsWithPublishedArticlesRow struct {
	Slug            string    `json:"slug"`
	DisplayName     string    `json:"display_name"`
	LastPublishedAt time.Time `json:"last_published_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// ListAuthorsWithPublishedArticles: active users with >= 1 published article (sitemap).
func (q *Queries) ListAuthorsWithPublishedArticles(ctx context.Context) ([]ListAuthorsWithPublishedArticlesRow, error) {
	rows, err := q.db.Query(ctx, listAuthorsWithPublishedArticles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuthorsWithPublishedArticlesRow{}
	for rows.Next() {
		var i ListAuthorsWithPublishedArticlesRow
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.LastPublishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionCodes = `-- name: ListUserPermissionCodes :many
SELECT DISTINCT p.code
FROM user_roles ur
JOIN role_permissions rp ON rp.role_id = ur.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
ORDER BY p.code
`

func (q *Queries) ListUserPermissionCodes(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissionCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.code, r.name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.code
`

type ListUserRolesRow struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) ListUserRoles(ctx context.Context, userID int64) ([]ListUserRolesRow, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRolesRow{}
	for rows.Next() {
		var i ListUserRolesRow
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRolesByUserIDs = `-- name: ListUserRolesByUserIDs :many
SELECT ur.user_id, r.id, r.code, r.name
FROM user_roles ur
JOIN roles r ON r.id = ur.role_id
WHERE ur.user_id = ANY($1::bigint[])
ORDER BY ur.user_id, r.code
`

type ListUserRolesByUserIDsRow struct {
	UserID int64  `json:"user_id"`
	ID     int64  `json:"id"`
	Code   string `json:"code"`
	Name   string `json:"name"`
}

func (q *Queries) ListUserRolesByUserIDs(ctx context.Context, userIds []int64) ([]ListUserRolesByUserIDsRow, error) {
	rows, err := q.db.Query(ctx, listUserRolesByUserIDs, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRolesByUserIDsRow{}
	for rows.Next() {
		var i ListUserRolesByUserIDsRow
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.Code,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.email, u.display_name, u.slug, u.title, u.bio, u.avatar_media_id,
       u.can_login, u.is_active, u.last_login_at, u.perm_version, u.created_at, u.updated_at
FROM users u
WHERE ($1::text IS NULL
       OR u.display_name ILIKE '%' || $1::text || '%'
       OR u.email::text ILIKE '%' || $1::text || '%')
  AND ($2::boolean IS NULL OR u.can_login = $2::boolean)
  AND ($3::boolean IS NULL OR u.is_active = $3::boolean)
  AND ($4::text IS NULL OR EXISTS (
        SELECT 1 FROM user_roles ur JOIN roles r ON r.id = ur.role_id
        WHERE ur.user_id = u.id AND r.code = $4::text))
ORDER BY u.display_name, u.id
LIMIT $6 OFFSET $5
`

type ListUsersParams struct {
	Q        *string `json:"q"`
	CanLogin *bool   `json:"can_login"`
	IsActive *bool   `json:"is_active"`
	RoleCode *string `json:"role_code"`
	Offset   int32   `json:"offset"`
	Limit    int32   `json:"limit"`
}

type ListUsersRow struct {
	ID            int64      `json:"id"`
	Email         *string    `json:"email"`
	DisplayName   string     `json:"display_name"`
	Slug          string     `json:"slug"`
	Title         *string    `json:"title"`
	Bio           *string    `json:"bio"`
	AvatarMediaID *int64     `json:"avatar_media_id"`
	CanLogin      bool       `json:"can_login"`
	IsActive      bool       `json:"is_active"`
	LastLoginAt   *time.Time `json:"last_login_at"`
	PermVersion   int32      `json:"perm_version"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Q,
		arg.CanLogin,
		arg.IsActive,
		arg.RoleCode,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.Slug,
			&i.Title,
			&i.Bio,
			&i.AvatarMediaID,
			&i.CanLogin,
			&i.IsActive,
			&i.LastLoginAt,
			&i.PermVersion,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, display_name, slug, title, bio, avatar_media_id, is_active
FROM users
WHERE id = ANY($1::bigint[])
ORDER BY id
`

type ListUsersByIDsRow struct {
	ID            int64   `json:"id"`
	DisplayName   string  `json:"display_name"`
	Slug          string  `json:"slug"`
	Title         *string `json:"title"`
	Bio           *string `json:"bio"`
	AvatarMediaID *int64  `json:"avatar_media_id"`
	IsActive      bool    `json:"is_active"`
}

func (q *Queries) ListUsersByIDs(ctx context.Context, ids []int64) ([]ListUsersByIDsRow, error) {
	rows, err := q.db.Query(ctx, listUsersByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByIDsRow{}
	for rows.Next() {
		var i ListUsersByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Slug,
			&i.Title,
			&i.Bio,
			&i.AvatarMediaID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users SET is_active = $1 WHERE id = $2
`

type SetUserActiveParams struct {
	IsActive bool  `json:"is_active"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.IsActive, arg.ID)
	return err
}

const touchLastLogin = `-- name: TouchLastLogin :exec
UPDATE users SET last_login_at = now() WHERE id = $1
`

func (q *Queries) TouchLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchLastLogin, id)
	return err
}

const updateUserAdmin = `-- name: UpdateUserAdmin :one
UPDATE users
SET email = $1::citext,
    display_name = $2,
    slug = $3,
    title = $4,
    bio = $5,
    avatar_media_id = $6,
    can_login = $7,
    is_active = $8
WHERE id = $9
RETURNING id, email, display_name, slug, title, bio, avatar_media_id,
          can_login, is_active, last_login_at, perm_version, created_at, updated_at
`

type UpdateUserAdminParams struct {
	Email         *string `json:"email"`
	DisplayName   string  `json:"display_name"`
	Slug          string  `json:"slug"`
	Title         *string `json:"title"`
	Bio           *string `json:"bio"`
	AvatarMediaID *int64  `json:"avatar_media_id"`
	CanLogin      bool    `json:"can_login"`
	IsActive      bool    `json:"is_active"`
	ID            int64   `json:"id"`
}

type UpdateUserAdminRow struct {
	ID            int64      `json:"id"`
	Email         *string    `json:"email"`
	DisplayName   string     `json:"display_name"`
	Slug          string     `json:"slug"`
	Title         *string    `json:"title"`
	Bio           *string    `json:"bio"`
	AvatarMediaID *int64     `json:"avatar_media_id"`
	CanLogin      bool       `json:"can_login"`
	IsActive      bool       `json:"is_active"`
	LastLoginAt   *time.Time `json:"last_login_at"`
	PermVersion   int32      `json:"perm_version"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateUserAdmin(ctx context.Context, arg UpdateUserAdminParams) (UpdateUserAdminRow, error) {
	row := q.db.QueryRow(ctx, updateUserAdmin,
		arg.Email,
		arg.DisplayName,
		arg.Slug,
		arg.Title,
		arg.Bio,
		arg.AvatarMediaID,
		arg.CanLogin,
		arg.IsActive,
		arg.ID,
	)
	var i UpdateUserAdminRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Slug,
		&i.Title,
		&i.Bio,
		&i.AvatarMediaID,
		&i.CanLogin,
		&i.IsActive,
		&i.LastLoginAt,
		&i.PermVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash *string `json:"password_hash"`
	ID           int64   `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $1,
    title = $2,
    bio = $3,
    avatar_media_id = $4
WHERE id = $5
RETURNING id, email, display_name, slug, title, bio, avatar_media_id,
          can_login, is_active, last_login_at, perm_version, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName   string  `json:"display_name"`
	Title         *string `json:"title"`
	Bio           *string `json:"bio"`
	AvatarMediaID *int64  `json:"avatar_media_id"`
	ID            int64   `json:"id"`
}

type UpdateUserProfileRow struct {
	ID            int64      `json:"id"`
	Email         *string    `json:"email"`
	DisplayName   string     `json:"display_name"`
	Slug          string     `json:"slug"`
	Title         *string    `json:"title"`
	Bio           *string    `json:"bio"`
	AvatarMediaID *int64     `json:"avatar_media_id"`
	CanLogin      bool       `json:"can_login"`
	IsActive      bool       `json:"is_active"`
	LastLoginAt   *time.Time `json:"last_login_at"`
	PermVersion   int32      `json:"perm_version"`
	CreatedAt     time.Time  `json:"created_at"`
	UpdatedAt     time.Time  `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Title,
		arg.Bio,
		arg.AvatarMediaID,
		arg.ID,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Slug,
		&i.Title,
		&i.Bio,
		&i.AvatarMediaID,
		&i.CanLogin,
		&i.IsActive,
		&i.LastLoginAt,
		&i.PermVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
