// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: videos.sql

package dbgen

import (
	"context"
	"time"
)

const countPublishedVideos = `-- name: CountPublishedVideos :one
SELECT count(*) FROM videos
WHERE status = 'published' AND published_at <= now()
  AND ($1::bigint IS NULL OR id <> $1::bigint)
`

func (q *Queries) CountPublishedVideos(ctx context.Context, excludeID *int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedVideos, excludeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVideosAdmin = `-- name: CountVideosAdmin :one
SELECT count(*) FROM videos
WHERE ($1::text IS NULL OR title ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR status = $2::text)
`

type CountVideosAdminParams struct {
	Q      *string `json:"q"`
	Status *string `json:"status"`
}

func (q *Queries) CountVideosAdmin(ctx context.Context, arg CountVideosAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVideosAdmin, arg.Q, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVideo = `-- name: CreateVideo :one

INSERT INTO videos (
  title, slug, youtube_id, description, duration_seconds, view_count, thumbnail_media_id,
  published_at, is_featured, status, created_by, updated_by)
VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  COALESCE($8::timestamptz, now()), $9, $10,
  $11, $12)
RETURNING id, title, slug, youtube_id, description, duration_seconds, view_count, thumbnail_media_id, published_at, is_featured, status, created_by, updated_by, created_at, updated_at
`

type CreateVideoParams struct {
	Title            string     `json:"title"`
	Slug             string     `json:"slug"`
	YoutubeID        string     `json:"youtube_id"`
	Description      *string    `json:"description"`
	DurationSeconds  *int32     `json:"duration_seconds"`
	ViewCount        *int64     `json:"view_count"`
	ThumbnailMediaID *int64     `json:"thumbnail_media_id"`
	PublishedAt      *time.Time `json:"published_at"`
	IsFeatured       bool       `json:"is_featured"`
	Status           string     `json:"status"`
	CreatedBy        *int64     `json:"created_by"`
	UpdatedBy        *int64     `json:"updated_by"`
}

// Public video queries: status = 'published' AND published_at <= now().
func (q *Queries) CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createVideo,
		arg.Title,
		arg.Slug,
		arg.YoutubeID,
		arg.Description,
		arg.DurationSeconds,
		arg.ViewCount,
		arg.ThumbnailMediaID,
		arg.PublishedAt,
		arg.IsFeatured,
		arg.Status,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.YoutubeID,
		&i.Description,
		&i.DurationSeconds,
		&i.ViewCount,
		&i.ThumbnailMediaID,
		&i.PublishedAt,
		&i.IsFeatured,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :execrows
DELETE FROM videos WHERE id = $1
`

func (q *Queries) DeleteVideo(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVideo, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPublishedVideoBySlug = `-- name: GetPublishedVideoBySlug :one
SELECT id, title, slug, youtube_id, description, duration_seconds, view_count, thumbnail_media_id, published_at, is_featured, status, created_by, updated_by, created_at, updated_at FROM videos WHERE slug = $1 AND status = 'published' AND published_at <= now()
`

func (q *Queries) GetPublishedVideoBySlug(ctx context.Context, slug string) (Video, error) {
	row := q.db.QueryRow(ctx, getPublishedVideoBySlug, slug)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.YoutubeID,
		&i.Description,
		&i.DurationSeconds,
		&i.ViewCount,
		&i.ThumbnailMediaID,
		&i.PublishedAt,
		&i.IsFeatured,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideo = `-- name: GetVideo :one
SELECT id, title, slug, youtube_id, description, duration_seconds, view_count, thumbnail_media_id, published_at, is_featured, status, created_by, updated_by, created_at, updated_at FROM videos WHERE id = $1
`

func (q *Queries) GetVideo(ctx context.Context, id int64) (Video, error) {
	row := q.db.QueryRow(ctx, getVideo, id)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.YoutubeID,
		&i.Description,
		&i.DurationSeconds,
		&i.ViewCount,
		&i.ThumbnailMediaID,
		&i.PublishedAt,
		&i.IsFeatured,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoBySlug = `-- name: GetVideoBySlug :one
SELECT id, title, slug, youtube_id, description, duration_seconds, view_count, thumbnail_media_id, published_at, is_featured, status, created_by, updated_by, created_at, updated_at FROM videos WHERE slug = $1
`

func (q *Queries) GetVideoBySlug(ctx context.Context, slug string) (Video, error) {
	row := q.db.QueryRow(ctx, getVideoBySlug, slug)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.YoutubeID,
		&i.Description,
		&i.DurationSeconds,
		&i.ViewCount,
		&i.ThumbnailMediaID,
		&i.PublishedAt,
		&i.IsFeatured,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPublishedVideos = `-- name: ListPublishedVideos :many
SELECT id, title, slug, youtube_id, description, duration_seconds, view_count, thumbnail_media_id, published_at, is_featured, status, created_by, updated_by, created_at, updated_at FROM videos
WHERE status = 'published' AND published_at <= now()
  AND ($1::bigint IS NULL OR id <> $1::bigint)
ORDER BY is_featured DESC, published_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListPublishedVideosParams struct {
	ExcludeID *int64 `json:"exclude_id"`
	Offset    int32  `json:"offset"`
	Limit     int32  `json:"limit"`
}

// ListPublishedVideos: exclude_id NULL = none (detail "other videos").
func (q *Queries) ListPublishedVideos(ctx context.Context, arg ListPublishedVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listPublishedVideos, arg.ExcludeID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.YoutubeID,
			&i.Description,
			&i.DurationSeconds,
			&i.ViewCount,
			&i.ThumbnailMediaID,
			&i.PublishedAt,
			&i.IsFeatured,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedVideosForSitemap = `-- name: ListPublishedVideosForSitemap :many
SELECT slug, updated_at FROM videos
WHERE status = 'published' AND published_at <= now()
ORDER BY published_at DESC, id DESC
`

type ListPublishedVideosForSitemapRow struct {
	Slug      string    `json:"slug"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) ListPublishedVideosForSitemap(ctx context.Context) ([]ListPublishedVideosForSitemapRow, error) {
	rows, err := q.db.Query(ctx, listPublishedVideosForSitemap)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedVideosForSitemapRow{}
	for rows.Next() {
		var i ListPublishedVideosForSitemapRow
		if err := rows.Scan(&i.Slug, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVideosAdmin = `-- name: ListVideosAdmin :many
SELECT id, title, slug, youtube_id, description, duration_seconds, view_count, thumbnail_media_id, published_at, is_featured, status, created_by, updated_by, created_at, updated_at FROM videos
WHERE ($1::text IS NULL OR title ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY published_at DESC, id DESC
LIMIT $4 OFFSET $3
`

type ListVideosAdminParams struct {
	Q      *string `json:"q"`
	Status *string `json:"status"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) ListVideosAdmin(ctx context.Context, arg ListVideosAdminParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, listVideosAdmin,
		arg.Q,
		arg.Status,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Video{}
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.YoutubeID,
			&i.Description,
			&i.DurationSeconds,
			&i.ViewCount,
			&i.ThumbnailMediaID,
			&i.PublishedAt,
			&i.IsFeatured,
			&i.Status,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideo = `-- name: UpdateVideo :one
UPDATE videos
SET title = $1,
    slug = $2,
    youtube_id = $3,
    description = $4,
    duration_seconds = $5,
    view_count = $6,
    thumbnail_media_id = $7,
    published_at = COALESCE($8::timestamptz, published_at),
    is_featured = $9,
    status = $10,
    updated_by = $11
WHERE id = $12
RETURNING id, title, slug, youtube_id, description, duration_seconds, view_count, thumbnail_media_id, published_at, is_featured, status, created_by, updated_by, created_at, updated_at
`

type UpdateVideoParams struct {
	Title            string     `json:"title"`
	Slug             string     `json:"slug"`
	YoutubeID        string     `json:"youtube_id"`
	Description      *string    `json:"description"`
	DurationSeconds  *int32     `json:"duration_seconds"`
	ViewCount        *int64     `json:"view_count"`
	ThumbnailMediaID *int64     `json:"thumbnail_media_id"`
	PublishedAt      *time.Time `json:"published_at"`
	IsFeatured       bool       `json:"is_featured"`
	Status           string     `json:"status"`
	UpdatedBy        *int64     `json:"updated_by"`
	ID               int64      `json:"id"`
}

// UpdateVideo: published_at NULL keeps the stored value.
func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, updateVideo,
		arg.Title,
		arg.Slug,
		arg.YoutubeID,
		arg.Description,
		arg.DurationSeconds,
		arg.ViewCount,
		arg.ThumbnailMediaID,
		arg.PublishedAt,
		arg.IsFeatured,
		arg.Status,
		arg.UpdatedBy,
		arg.ID,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.YoutubeID,
		&i.Description,
		&i.DurationSeconds,
		&i.ViewCount,
		&i.ThumbnailMediaID,
		&i.PublishedAt,
		&i.IsFeatured,
		&i.Status,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const videoSlugExists = `-- name: VideoSlugExists :one
SELECT EXISTS (
  SELECT 1 FROM videos WHERE slug = $1::text AND id <> $2::bigint
) AS exists
`

type VideoSlugExistsParams struct {
	Slug      string `json:"slug"`
	ExcludeID int64  `json:"exclude_id"`
}

func (q *Queries) VideoSlugExists(ctx context.Context, arg VideoSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, videoSlugExists, arg.Slug, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
